"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "mn" | "en" | "cn";

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
}

const useLanguageStore = create<LanguageState>()(
    persist(
        (set) => ({
            language: "mn",
            setLanguage: (lang) => set({ language: lang }),
        }),
        {
            name: "language-storage",
        }
    )
);

const translations = {
    mn: {
        home: "Нүүр",
        packages: "Багцууд",
        myEsims: "Миний eSIM",
        profile: "Профайл",
        login: "Нэвтрэх",
        greeting: "Сайн байна уу",
        logout: "Гарах",
        save: "Хадгалах",
        saving: "Хадгалж байна...",
        appearance: "Харагдац",
        lightMode: "Өдөр",
        darkMode: "Шөнө",
        email: "И-мэйл хаяг",
        phone: "Утасны дугаар",
        phonePlaceholder: "Утасны дугаараа оруулна уу",
        back: "Буцах",
        loading: "Уншиж байна...",
        error: "Алдаа гарлаа",
        success: "Амжилттай",
        // AI Chat
        aiTitle: "Аяллын туслах",
        aiDescription: "Ухаалаг зөвлөх",
        aiGuestMode: "Зочин горим",
        aiThinking: "Бодож байна...",
        aiPlaceholder: "Ямар багц хайж байна вэ?",
        aiPopularPackages: "Түгээмэл багцууд:",
        aiSeeAll: "Бүх багцыг үзэх",
        aiCompatibilityWarning: "Сайн байна уу! Таны {device} eSIM дэмжихгүй байж магадгүй байна. ⚠️\n\nТа худалдан авалт хийхээсээ өмнө төхөөрөмжөө eSIM дэмждэг эсэхийг шалгаарай.",
        aiGreeting1: "Сайн байна уу! Та аль улс руу, хэд хоногоор аялах гэж байна вэ? 🌍✈️",
        aiGreeting2: "Сайн байна уу! Танд аялах улсад чинь тохирох eSIM багц олоход туслах уу? 🗺️✨",
        aiGreeting3: "Сайн уу! Дараагийн аялал хаашаа вэ? Би танд хамгийн хямд багцыг олж өгч чадна. 🚀",
        aiGreeting4: "Сайн байна уу! Та аялах улсаа хэлээрэй, би хамгийн шилдэг багцуудыг санал болгоё. 💡",
        // Home
        homeHeroTitle: "Холболт хаана ч",
        homeHeroSubtitle: "Таны дэлхийн гарц",
        homeHeroDesc: "Дэлхийн 200 гаруй улсад хамгийн хямд үнээр интернетэд холбогдоорой.",
        homeSearchPlaceholder: "Хаашаа аялах вэ?",
        homeDuration7: "7 хоног",
        homeDuration15: "15 хоног",
        homePopularTitle: "Түгээмэл улсууд",
        homeFeaturedTitle: "Онцлох багцууд",
        homeAiAssistantTitle: "Ухаалаг аяллын туслах 🤖",
        homeAiAssistantDesc: "Та хаашаа явахаа хэлэхэд л хангалттай, би танд хамгийн тохиромжтой багцыг санал болгоно.",
        homeAiAssistantExample: "Жишээ нь: \"Япон 2 долоо хоног\"",
        homeAiFeature1: "💬 Олон хэлээр ярьдаг",
        homeAiFeature2: "⚡ Шуурхай хариу",
        homeAiFeature3: "🎯 Хувийн зөвлөгөө",
        day: "хоног",
        viewPackages: "Багцуудыг үзэх",
        all: "Бүгд",
        allCountries: "Бүх улс",
        searchPackagesPlaceholder: "Улс, багц хайх...",
        countPackages: "{count} багц",
        noPackagesFound: "Багц олдсонгүй",
        noPackagesDesc: "Хайлт эсвэл шүүлтүүрээ өөрчлөөд үзнэ үү.",
        clearFilters: "Шүүлтүүр цэвэрлэх",
        loadingMore: "Ачааллаж байна...",
        scrollMore: "Доош гүйлгэж илүү ихийг үзнэ үү",
        allPackagesShown: "Бүх {count} багц харагдлаа ✓",
        plusCountries: "+ {count} улс",
        myEsimsHeroTitle: "Миний eSIM",
        myEsimsHeroDesc: "Худалдаж авсан багцуудаа эндээс удирдаарай",
        active: "Идэвхтэй",
        history: "Түүх",
        loginRequired: "Нэвтрэх шаардлагатай",
        loginRequiredDesc: "Та өөрийн захиалгуудыг харахын тулд системд нэвтэрч орно уу.",
        noActiveEsims: "Идэвхтэй eSIM алга",
        noActiveEsimsDesc: "Дэлхийн хаана ч холбогдох боломжтой eSIM багцаа сонгоод аялалаа эхлүүлээрэй.",
        noHistory: "Түүх хоосон байна",
        noHistoryDesc: "Таны худалдан авалтын түүх энд харагдах болно.",
        selectPackage: "Багц сонгох",
        statusActive: "Идэвхтэй",
        statusPending: "Хүлээж байна",
        statusCompleted: "Дууссан",
        dataUsage: "Дата ашиглалт",
        daysRemaining: "{count} хоног үлдсэн",
        esimDetails: "eSIM Дэлгэрэнгүй",
        qrScanInstructions: "Доорх QR кодыг уншуулж eSIM-ээ идэвхжүүлээрэй",
        downloadQr: "QR татах (Зураг)",
        download: "Татах",
        qrOneTime: "Код зөвхөн нэг удаа уншигдана",
        manualEntry: "Гараар оруулах код",
        iccid: "ICCID (Сериал дугаар)",
        sendToFriend: "Найздаа илгээх",
        installationGuide: "Суулгах заавар харах",
        featured: "Онцлох",
        regional: "Бүсийн",
        vpnIncluded: "VPN-тэй",
        price: "Үнэ",
        validity: "Хугацаа",
        coverage: "Хамрах",
        activation: "Идэвхжих",
        instant: "Шууд",
        packageDetails: "Багцын дэлгэрэнгүй",
        compatibleDevices: "Нийцтэй төхөөрөмжүүд",
        importantNotes: "Анхаарах зүйлс",
        totalAmount: "Нийт төлөх",
        buyNow: "Авах",
        checkoutTitle: "Захиалга баталгаажуулах",
        receiveEmail: "Хүлээн авах имэйл",
        invalidEmail: "Буруу форматтай имэйл байна",
        emailNote: "QR код энэ хаягаар илгээгдэнэ",
        paymentMethod: "Төлбөрийн хэлбэр",
        qpayDesc: "Банкны аппаар төлөх",
        comingSoon: "Тун удахгүй",
        payNow: "Төлбөр төлөх",
        paymentSuccess: "Төлбөр амжилттай!",
        preparingEsim: "eSIM-ийг бэлтгэж байна...",
        orderConfirmed: "Таны захиалга баталгаажлаа. Имэйлээ шалгана уу.",
        orderNumber: "Захиалгын дугаар",
        backToHome: "Нүүр хуудас руу буцах",
        checkPayment: "Төлбөр шалгах",
        waitingPayment: "Төлбөр хүлээж байна...",
        bankAppPay: "Банкны аппаар төлөх",
        summary: "Товчоо",
        package: "Багц",
        // Technical Info
        speed4G5G: "4G/5G өндөр хурдны сүлжээ",
        noSpeedLimit: "Хурдны хязгааргүй (High Speed)",
        hotspotSupport: "Hotspot цацах боломжтой",
        activationOnUse: "Ашиглаж эхэлснээс хойш хугацаа тоологдоно",
        emailDeliveryInfo: "eSIM QR код таны и-мэйл хаягаар 1-5 минутын дотор ирнэ. Та зөвхөн eSIM дэмждэг утастай байх шаардлагатай.",
        // Country Names
        country_JP: "Япон",
        country_KR: "Солонгос",
        country_CN: "Хятад",
        country_TH: "Тайланд",
        country_SG: "Сингапур",
        country_VN: "Вьетнам",
        country_TR: "Турк",
        country_US: "Америк",
        country_RU: "Орос",
        country_KZ: "Казахстан",
        country_DE: "Герман",
        country_FR: "Франц",
        country_IT: "Итали",
        country_ES: "Испани",
        country_NL: "Нидерланд",
        country_GB: "Их Британи",
        country_EU: "Европ",
        country_AL: "Албани",
        country_AE: "Арабын Нэгдсэн Эмират",
        country_HK: "Хонг Конг",
        country_TW: "Тайвань",
        // Device Names
        devicePhone: "Утас",
        yourPhone: "Таны утас",
        compatibleIphone: "iPhone XR, 11, 12, 13, 14, 15, 16 болон шинэ загварууд (Dual SIM-г анхаарах).",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold загварууд.",
        compatiblePixel: "Google Pixel 3, 4, 5, 6, 7, 8, 9 болон шинэ загварууд.",
    },
    en: {
        home: "Home",
        packages: "Packages",
        myEsims: "My eSIM",
        profile: "Profile",
        login: "Login",
        greeting: "Hello",
        logout: "Logout",
        save: "Save",
        saving: "Saving...",
        appearance: "Appearance",
        lightMode: "Light",
        darkMode: "Dark",
        email: "Email Address",
        phone: "Phone Number",
        phonePlaceholder: "Enter your phone number",
        back: "Back",
        loading: "Loading...",
        error: "An error occurred",
        success: "Success",
        // AI Chat
        aiTitle: "AI Assistant",
        aiDescription: "Smart Advisor",
        aiGuestMode: "Guest Mode (eSIM only)",
        aiThinking: "Thinking...",
        aiPlaceholder: "What package are you looking for?",
        aiPopularPackages: "Popular Searches:",
        aiSeeAll: "See all packages",
        aiCompatibilityWarning: "Hello! Your {device} might not support eSIM. ⚠️\n\nPlease check compatibility before purchasing.",
        aiGreeting1: "Hello! Where are you traveling to, and for how long? 🌍✈️",
        aiGreeting2: "Hello! Can I help you find a suitable eSIM package for your trip? 🗺️✨",
        aiGreeting3: "Hi! Where's your next trip? I can find the best package for you. 🚀",
        aiGreeting4: "Hello! Tell me which country you're traveling to, and I'll show you the best packages. 💡",
        // Home
        homeHeroTitle: "Connectivity Everywhere",
        homeHeroSubtitle: "Your Global Gateway",
        homeHeroDesc: "Connect to the internet in 200+ countries at the most affordable prices.",
        homeSearchPlaceholder: "Where are you going?",
        homeDuration7: "7 Days",
        homeDuration15: "15 Days",
        homePopularTitle: "Popular Countries",
        homeFeaturedTitle: "Featured Packages",
        homeAiAssistantTitle: "Smart Travel Assistant 🤖",
        homeAiAssistantDesc: "Just tell me where you're going, and I'll recommend the best package for you.",
        homeAiAssistantExample: "Try: \"Japan for 2 weeks\"",
        homeAiFeature1: "💬 Multilingual",
        homeAiFeature2: "⚡ Instant Response",
        homeAiFeature3: "🎯 Personalized Advice",
        day: "days",
        viewPackages: "View Packages",
        all: "All",
        allCountries: "All Countries",
        searchPackagesPlaceholder: "Search countries, packages...",
        countPackages: "{count} packages",
        noPackagesFound: "No packages found",
        noPackagesDesc: "Try changing your search or filters.",
        clearFilters: "Clear Filters",
        loadingMore: "Loading...",
        scrollMore: "Scroll down for more",
        allPackagesShown: "All {count} packages shown ✓",
        plusCountries: "+ {count} countries",
        myEsimsHeroTitle: "My eSIMs",
        myEsimsHeroDesc: "Manage your purchased packages here",
        active: "Active",
        history: "History",
        loginRequired: "Login Required",
        loginRequiredDesc: "Please login to view your orders.",
        noActiveEsims: "No active eSIMs",
        noActiveEsimsDesc: "Choose an eSIM package and start your journey.",
        noHistory: "History is empty",
        noHistoryDesc: "Your purchase history will appear here.",
        selectPackage: "Select Package",
        statusActive: "Active",
        statusPending: "Pending",
        statusCompleted: "Completed",
        dataUsage: "Data Usage",
        daysRemaining: "{count} days remaining",
        esimDetails: "eSIM Details",
        qrScanInstructions: "Scan the QR code below to activate your eSIM",
        downloadQr: "Download QR (Image)",
        download: "Download",
        qrOneTime: "Code can only be scanned once",
        manualEntry: "Manual Entry Code",
        iccid: "ICCID (Serial Number)",
        sendToFriend: "Send to Friend",
        installationGuide: "View Installation Guide",
        featured: "Featured",
        regional: "Regional",
        vpnIncluded: "VPN Included",
        price: "Price",
        validity: "Validity",
        coverage: "Coverage",
        activation: "Activation",
        instant: "Instant",
        packageDetails: "Package Details",
        compatibleDevices: "Compatible Devices",
        importantNotes: "Important Notes",
        totalAmount: "Total Amount",
        buyNow: "Buy Now",
        checkoutTitle: "Checkout",
        receiveEmail: "Contact Email",
        invalidEmail: "Invalid email format",
        emailNote: "QR code will be sent to this email",
        paymentMethod: "Payment Method",
        qpayDesc: "Pay with Banking App",
        comingSoon: "Coming Soon",
        payNow: "Pay Now",
        paymentSuccess: "Payment Success!",
        preparingEsim: "Preparing your eSIM...",
        orderConfirmed: "Your order is confirmed. Please check your email.",
        orderNumber: "Order Number",
        backToHome: "Back to Home",
        checkPayment: "Check Payment",
        waitingPayment: "Waiting for payment...",
        bankAppPay: "Pay with Bank App",
        summary: "Summary",
        package: "Package",
        // Technical Info
        speed4G5G: "4G/5G High Speed Network",
        noSpeedLimit: "No Speed Limit (High Speed)",
        hotspotSupport: "Hotspot/Tethering Supported",
        activationOnUse: "Validity starts upon first connection",
        emailDeliveryInfo: "eSIM QR code will arrive via email within 1-5 minutes. Ensure your device is eSIM compatible.",
        // Country Names
        country_JP: "Japan",
        country_KR: "South Korea",
        country_CN: "China",
        country_TH: "Thailand",
        country_SG: "Singapore",
        country_VN: "Vietnam",
        country_TR: "Turkey",
        country_US: "USA",
        country_RU: "Russia",
        country_KZ: "Kazakhstan",
        country_DE: "Germany",
        country_FR: "France",
        country_IT: "Italy",
        country_ES: "Spain",
        country_NL: "Netherlands",
        country_GB: "United Kingdom",
        country_EU: "Europe",
        country_AL: "Albania",
        country_AE: "United Arab Emirates",
        country_HK: "Hong Kong",
        country_TW: "Taiwan",
        // Device Names
        devicePhone: "Phone",
        yourPhone: "Your Phone",
        compatibleIphone: "iPhone XS, XR and all newer models (Watch for Dual SIM versions).",
        compatibleSamsung: "Galaxy S20 or newer, Z Fold, Z Flip models.",
        compatiblePixel: "Pixel 3 and all newer models.",
    },
    cn: {
        home: "首页",
        packages: "套餐",
        myEsims: "我的eSIM",
        profile: "个人资料",
        login: "登录",
        greeting: "你好",
        logout: "注销",
        save: "保存",
        saving: "正在保存...",
        appearance: "外观",
        lightMode: "日间",
        darkMode: "夜间",
        email: "电子邮箱",
        phone: "电话号码",
        phonePlaceholder: "输入您的电话号码",
        back: "返回",
        loading: "加载中...",
        error: "发生错误",
        success: "成功",
        // AI Chat
        aiTitle: "旅行助手",
        aiDescription: "智能建议",
        aiGuestMode: "游客模式 (仅限 eSIM)",
        aiThinking: "思考中...",
        aiPlaceholder: "您在寻找什么套餐？",
        aiPopularPackages: "热门套餐：",
        aiSeeAll: "查看所有套餐",
        aiCompatibilityWarning: "您好！您的 {device} 可能不支持 eSIM。⚠️\n\n请在购买前检查设备兼容性。",
        aiGreeting1: "您好！您要去哪里旅行，打算呆多久？🌍✈️",
        aiGreeting2: "您好！我可以帮您找到适合旅行的 eSIM 套餐吗？🗺️✨",
        aiGreeting3: "嗨！您的下一次旅行去哪里？我可以为您找到最合适的套餐。🚀",
        aiGreeting4: "您好！告诉我您要去哪个国家，我会为您推荐最合适的套餐。💡",
        // Home
        homeHeroTitle: "全球互联",
        homeHeroSubtitle: "您的全球门户",
        homeHeroDesc: "以最实惠的价格在 200 多个国家/地区连接互联网。",
        homeSearchPlaceholder: "您要去哪里？",
        homeDuration7: "7天",
        homeDuration15: "15天",
        homePopularTitle: "热门国家",
        homeFeaturedTitle: "推荐套餐",
        homeAiAssistantTitle: "智能旅行助手 🤖",
        homeAiAssistantDesc: "只需告诉我您要去哪里，我就会为您推荐最合适的套餐。",
        homeAiAssistantExample: "尝试：\"日本两周\"",
        homeAiFeature1: "💬 多语言支持",
        homeAiFeature2: "⚡ 即时响应",
        homeAiFeature3: "🎯 个性化建议",
        day: "天",
        viewPackages: "查看套餐",
        all: "全部",
        allCountries: "所有国家",
        searchPackagesPlaceholder: "搜索国家或套餐...",
        countPackages: "{count} 个套餐",
        noPackagesFound: "未找到套餐",
        noPackagesDesc: "请尝试更改搜索或过滤器。",
        clearFilters: "清除过滤器",
        loadingMore: "加载中...",
        scrollMore: "向下滑动查看更多",
        allPackagesShown: "已显示全部 {count} 个套餐 ✓",
        plusCountries: "+ {count} 个国家",
        myEsimsHeroTitle: "我的 eSIM",
        myEsimsHeroDesc: "在此管理您购买的套餐",
        active: "激活",
        history: "历史",
        loginRequired: "需要登录",
        loginRequiredDesc: "请登录以查看您的订单。",
        noActiveEsims: "没有激活的 eSIM",
        noActiveEsimsDesc: "选择一个 eSIM 套餐并开始您的旅程。",
        noHistory: "历史记录为空",
        noHistoryDesc: "您的购买历史将显示在这里。",
        selectPackage: "选择套餐",
        statusActive: "激活",
        statusPending: "待处理",
        statusCompleted: "已完成",
        dataUsage: "数据使用量",
        daysRemaining: "剩余 {count} 天",
        esimDetails: "eSIM 详情",
        qrScanInstructions: "扫描下方二维码以激活您的 eSIM",
        downloadQr: "下载二维码 (图片)",
        download: "下载",
        qrOneTime: "代码只能扫描一次",
        manualEntry: "手动输入代码",
        iccid: "ICCID (序列号)",
        sendToFriend: "发送给朋友",
        installationGuide: "查看安装指南",
        featured: "推荐",
        regional: "地区",
        vpnIncluded: "包含 VPN",
        price: "价格",
        validity: "有效期",
        coverage: "覆盖范围",
        activation: "激活",
        instant: "立即",
        packageDetails: "套餐详情",
        compatibleDevices: "兼容设备",
        importantNotes: "重要提示",
        totalAmount: "应付总额",
        buyNow: "立即购买",
        checkoutTitle: "结账",
        receiveEmail: "联系邮箱",
        invalidEmail: "邮箱格式不正确",
        emailNote: "二维码将发送至此邮箱",
        paymentMethod: "付款方式",
        qpayDesc: "使用银行应用付款",
        comingSoon: "即将推出",
        payNow: "立即付款",
        paymentSuccess: "支付成功！",
        preparingEsim: "正在准备您的 eSIM...",
        orderConfirmed: "您的订单已确认。请查看您的邮箱。",
        orderNumber: "订单编号",
        backToHome: "返回首页",
        checkPayment: "检查支付状态",
        waitingPayment: "正在等待付款...",
        bankAppPay: "银行应用付款",
        summary: "摘要",
        package: "套餐",
        // Technical Info
        speed4G5G: "4G/5G 高速网络",
        noSpeedLimit: "不限速 (高速)",
        hotspotSupport: "支持热点分享",
        activationOnUse: "首次使用时开始计算有效期",
        emailDeliveryInfo: "eSIM 二维码将在 1-5 分钟内通过邮件送达。请确保您的设备支持 eSIM。",
        // Country Names
        country_JP: "日本",
        country_KR: "韩国",
        country_CN: "中国",
        country_TH: "泰国",
        country_SG: "新加坡",
        country_VN: "越南",
        country_TR: "土耳其",
        country_US: "美国",
        country_RU: "俄罗斯",
        country_KZ: "哈萨克斯坦",
        country_DE: "德国",
        country_FR: "法国",
        country_IT: "意大利",
        country_ES: "西班牙",
        country_NL: "荷兰",
        country_GB: "英国",
        country_EU: "欧洲",
        country_AL: "阿尔巴尼亚",
        country_AE: "阿联酋",
        country_HK: "香港",
        country_TW: "台湾",
        // Device Names
        devicePhone: "手机",
        yourPhone: "您的手机",
        compatibleIphone: "iPhone XS, XR 及所有较新型号（注意双卡版本）。",
        compatibleSamsung: "Galaxy S20 或更新机型，Z Fold，Z Flip。",
        compatiblePixel: "Pixel 3 及所有较新型号。",
    }
};

const LanguageContext = createContext<{
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
} | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const { language, setLanguage } = useLanguageStore();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    const t = (key: string) => {
        const langData = translations[language] as Record<string, string>;
        const fallbackData = translations.mn as Record<string, string>;
        return langData[key] || fallbackData[key] || key;
    };

    if (!mounted) return null;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useTranslation() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useTranslation must be used within a LanguageProvider");
    }
    return context;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return { language: context.language, setLanguage: context.setLanguage };
}
