"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "mn" | "en" | "cn";

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
}

const useLanguageStore = create<LanguageState>()(
    persist(
        (set) => ({
            language: "mn",
            setLanguage: (lang) => set({ language: lang }),
        }),
        {
            name: "language-storage",
        }
    )
);

export const translations = {
    mn: {
        home: "Нүүр",
        packages: "Багцууд",
        myEsims: "Миний eSIM",
        profile: "Профайл",
        myProfile: "Миний мэдээлэл",
        user: "Хэрэглэгч",
        login: "Нэвтрэх",
        greeting: "Сайн байна уу",
        logout: "Гарах",
        save: "Хадгалах",
        saving: "Хадгалж байна...",
        appearance: "Харагдац",
        lightMode: "Өдөр",
        darkMode: "Шөнө",
        email: "И-мэйл хаяг",
        phone: "Утасны дугаар",
        phonePlaceholder: "Утасны дугаараа оруулна уу",
        back: "Буцах",
        loading: "Уншиж байна...",
        error: "Алдаа гарлаа",
        success: "Амжилттай",
        eSimPlatform: "eSIM Платформ",
        // Auth
        welcomeBack: "Эргэн тавтай морил",
        signUp: "Шинээр бүртгүүлэх",
        authSubtitle: "GateSIM-д нэгдэн дэлхийн хаана ч холбогдоорой",
        continueWithGoogle: "Google-ээр үргэлжлүүлэх",
        or: "эсвэл",
        password: "Нууц үг",
        noAccount: "Хаяг байхгүй юу?",
        alreadyRegistered: "Бүртгэлтэй юу?",
        phoneOptional: "Утасны дугаар (Заавал биш)",
        continueWithEmail: "И-мэйлээр үргэлжлүүлэх",
        magicLinkSubtitle: "Бид таны и-мэйл рүү нэвтрэх түр линк илгээх болно",
        emailPlaceholder: "Таны и-мэйл хаяг",
        magicLinkSent: "Нэвтрэх линк илгээгдлээ. И-мэйлээ шалгана уу.",
        forgotPassword: "Нууц үг мартсан уу?",
        forgotPasswordDesc: "Бүртгэлтэй и-мэйл хаягаа оруулж нууц үг сэргээх линк авна уу",
        sendResetLink: "Сэргээх линк илгээх",
        resetEmailSent: "И-мэйл илгээгдлээ",
        resetEmailSentDesc: "Нууц үг сэргээх линк и-мэйлээр илгээгдлээ. Шалгана уу.",
        backToLogin: "Нэвтрэх рүү буцах",
        // Filters
        duration1_7: "1-7 хоног",
        duration8_15: "8-15 хоног",
        duration15Plus: "15+ хоног",
        packagesFound: "Нийт {count} багц олдлоо",
        countryEsimPackages: "{country} eSIM Багцууд",
        all: "Бүгд",
        unlimited: "Хязгааргүй",
        noPackagesMatch: "Сонгосон шүүлтүүрт тохирох багц олдсонгүй.",
        clearFilters: "Шүүлтүүр арилгах",
        allCountries: "Бүх улс",
        searchPackagesPlaceholder: "Улс, багц хайх...",
        countPackages: "{count} багц",
        noPackagesFound: "Багц олдсонгүй",
        noPackagesDesc: "Хайлт эсвэл шүүлтүүрээ өөрчлөөд үзнэ үү.",
        loadingMore: "Ачааллаж байна...",
        scrollMore: "Доош гүйлгэж илүү ихийг үзнэ үү",
        allPackagesShown: "Бүх {count} багц харагдлаа ✓",
        // Nav
        navHome: "Нүүр",
        navPackages: "Багцууд",
        navMyEsim: "Миний eSIM",
        navProfile: "Профайл",
        // AI Chat
        aiTitle: "Аяллын туслах",
        aiDescription: "Ухаалаг зөвлөх",
        aiGuestMode: "Зочин горим",
        aiThinking: "Бодож байна...",
        aiPlaceholder: "Ямар багц хайж байна вэ?",
        aiPopularPackages: "Түгээмэл багцууд:",
        aiSeeAll: "Бүх багцыг үзэх",
        aiCompatibilityWarning: "Сайн байна уу! Таны {device} eSIM дэмжихгүй байж магадгүй байна. ⚠️\n\nТа худалдан авалт хийхээсээ өмнө төхөөрөмжөө eSIM дэмждэг эсэхийг шалгаарай.",
        aiGreeting1: "Сайн байна уу! Та аль улс руу, хэд хоногоор аялах гэж байна вэ? 🌍✈️",
        aiGreeting2: "Сайн байна уу! Танд аялах улсад чинь тохирох eSIM багц олоход туслах уу? 🗺️✨",
        aiGreeting3: "Сайн уу! Дараагийн аялал хаашаа вэ? Би танд хамгийн хямд багцыг олж өгч чадна. 🚀",
        aiGreeting4: "Сайн байна уу! Та аялах улсаа хэлээрэй, би хамгийн шилдэг багцуудыг санал болгоё. 💡",
        // Home
        homeHeroTitle: "Connectivity Everywhere",
        homeHeroSubtitle: "Your Global Gateway",
        homeHeroDesc: "Дэлхийн 200 гаруй улсад хамгийн хямд үнээр интернетэд холбогдоорой.",
        homeSearchPlaceholder: "Хаашаа аялах вэ?",
        homeDuration7: "7 хоног",
        homeDuration15: "15 хоног",
        homePopularTitle: "Түгээмэл улсууд",
        homeFeaturedTitle: "Онцлох багцууд",
        homeAiAssistantTitle: "Ухаалаг аяллын туслах 🤖",
        homeAiAssistantDesc: "Та хаашаа явахаа хэлэхэд л хангалттай, би танд хамгийн тохиромжтой багцыг санал болгоно.",
        homeAiAssistantExample: "Жишээ нь: \"Япон 2 долоо хоног\"",
        homeAiFeature1: "💬 Олон хэлээр ярьдаг",
        homeAiFeature2: "⚡ Шуурхай хариу",
        homeAiFeature3: "🎯 Хувийн зөвлөгөө",
        day: "хоног",
        viewPackages: "Багцуудыг үзэх",
        homeAiExample1: "Япон 2 долоо хоног",
        homeAiExample2: "Солонгос 10 ГБ",
        plusCountries: "+ {count} улс",
        myEsimsHeroTitle: "Миний eSIM",
        myEsimsHeroDesc: "Худалдаж авсан багцуудаа эндээс удирдаарай",
        active: "Идэвхтэй",
        history: "Түүх",
        loginRequired: "Нэвтрэх шаардлагатай",
        loginRequiredDesc: "Та өөрийн захиалгуудыг харахын тулд системд нэвтэрч орно уу.",
        noActiveEsims: "Идэвхтэй eSIM алга",
        noActiveEsimsDesc: "Дэлхийн хаана ч холбогдох боломжтой eSIM багцаа сонгоод аялалаа эхлүүлээрэй.",
        noHistory: "Түүх хоосон байна",
        noHistoryDesc: "Таны худалдан авалтын түүх энд харагдах болно.",
        selectPackage: "Багц сонгох",
        statusActive: "Идэвхтэй",
        statusPending: "Хүлээж байна",
        statusCompleted: "Дууссан",
        dataUsage: "Дата ашиглалт",
        daysRemaining: "{count} хоног үлдсэн",
        select: "Сонгох",
        cancel: "Болих",
        selectAll: "Бүгдийг сонгох",
        delete: "Устгах",
        esimDetails: "eSIM Дэлгэрэнгүй",
        qrScanInstructions: "Доорх QR кодыг уншуулж eSIM-ээ идэвхжүүлээрэй",
        downloadQr: "QR татах (Зураг)",
        download: "Татах",
        qrOneTime: "Код зөвхөн нэг удаа уншигдана",
        manualEntry: "Гараар оруулах код",
        iccid: "ICCID (Сериал дугаар)",
        sendToFriend: "Найздаа илгээх",
        installationGuide: "Суулгах заавар харах",
        featured: "Онцлох",
        regional: "Бүсийн",
        vpnIncluded: "VPN-тэй",
        topUp: "Цэнэглэлт",
        newEsim: "Шинэ eSIM",
        topUpDesc: "Зөвхөн өмнө нь исим авсан хэрэглэгчдэд",
        topUpNoEsimError: "Танд цэнэглэх идэвхтэй eSIM байхгүй байна",
        topUpLoginRequired: "Цэнэглэлт авахын тулд та нэвтэрсэн байх шаардлагатай.",
        topUpProviderError: "Зөвхөн {provider}-ийн eSIM-ийг цэнэглэх боломжтой",
        incompatible: "Тохирохгүй байна",
        vpnFeatureTitle: "VPN-тэй тул бүх сошиал руу чөлөөтэй орно",
        vpnFeatureDesc: "Facebook, Instagram, Youtube, Google зэрэг хориглогдсон бүх сүлжээ рүү ямар нэгэн хязгаарлалтгүйгээр чөлөөтэй нэвтрэнэ.",
        newPackagesBannerTitle: "Шинэ eSIM авах",
        newPackagesBannerDesc: "Та дэлхийн 200 гаруй улсад хамгийн хямд үнээр аялалын дата авах боломжтой.",
        topUpPackagesBannerTitle: "eSIM цэнэглэх",
        topUpPackagesBannerDesc: "Өмнө нь GateSIM-ээс авсан идэвхтэй eSIM-ээ ашиглан хурдны хязгааргүй датагаар цэнэглээрэй.",
        price: "Үнэ",
        validity: "Хугацаа",
        coverage: "Хамрах",
        activation: "Идэвхжих",
        instant: "Шууд",
        packageDetails: "Багцын дэлгэрэнгүй",
        compatibleDevices: "Нийцтэй төхөөрөмжүүд",
        importantNotes: "Анхаарах зүйлс",
        totalAmount: "Нийт төлөх",
        buyNow: "Авах",
        checkoutTitle: "Захиалга баталгаажуулах",
        receiveEmail: "Хүлээн авах имэйл",
        invalidEmail: "Буруу форматтай имэйл байна",
        emailNote: "QR код энэ хаягаар илгээгдэнэ",
        paymentMethod: "Төлбөрийн хэлбэр",
        qpayDesc: "Банкны аппаар төлөх",
        internationalCard: "Олон улсын карт",
        comingSoon: "Тун удахгүй",
        payNow: "Төлбөр төлөх",
        paymentSuccess: "Төлбөр амжилттай!",
        preparingEsim: "eSIM-ийг бэлтгэж байна...",
        orderConfirmed: "Таны захиалга баталгаажлаа. Имэйлээ шалгана уу.",
        orderNumber: "Захиалгын дугаар",
        backToHome: "Нүүр хуудас руу буцах",
        checkPayment: "Төлбөр шалгах",
        waitingPayment: "Төлбөр хүлээж байна...",
        bankAppPay: "Банкны аппаар төлөх",
        summary: "Товчоо",
        package: "Багц",
        // Technical Info
        speed4G5G: "4G/5G өндөр хурдны сүлжээ",
        noSpeedLimit: "Хурдны хязгааргүй (High Speed)",
        hotspotSupport: "Hotspot цацах боломжтой",
        activationOnUse: "Ашиглаж эхэлснээс хойш хугацаа тоологдоно",
        emailDeliveryInfo: "eSIM QR код 'Миний eSIM' цэсэнд хадгалагдах (нэвтэрсэн хэрэглэгч) болон таны и-мэйл хаягаар 1-5 минутын дотор ирнэ. Та зөвхөн eSIM дэмждэг утастай байх шаардлагатай.",
        // Country Names
        country_JP: "Япон",
        country_KR: "Солонгос",
        country_CN: "Хятад",
        country_TH: "Тайланд",
        country_SG: "Сингапур",
        country_VN: "Вьетнам",
        country_TR: "Турк",
        country_US: "Америк",
        country_RU: "Орос",
        country_KZ: "Казахстан",
        country_DE: "Герман",
        country_FR: "Франц",
        country_IT: "Итали",
        country_ES: "Испани",
        country_NL: "Нидерланд",
        country_GB: "Их Британи",
        country_EU: "Европ",
        country_AL: "Албани",
        country_AE: "Арабын Нэгдсэн Эмират",
        country_HK: "Хонг Конг",
        country_TW: "Тайвань",
        // Device Names
        devicePhone: "Утас",
        yourPhone: "Таны утас",
        compatibleIphone: "iPhone XR, XS, 11, 12, 13, 14, 15, 16 болон шинэ загварууд. \n⚠️ Анхааруулга: Хятад, Хонконг, Макаогаас авсан iPhone (XS, 11, 12, 13, 14, 15... гэх мэт) ихэнх загварууд eSIM дэмждэггүй (2 сим карт ордог тул).",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold цувралууд. \n⚠️ Анхааруулга: Хятад, Хонконг, Макао хувилбарууд ихэвчлэн eSIM дэмждэггүй.",
        compatiblePixel: "Google Pixel 3, 3XL, 4, 4XL, 5... болон түүнээс хойшхи бүх загварууд.",
        // Expense Tracker
        aiScanReceipt: "Баримт уншуулах",
        aiScanDesc: "AI таны баримтыг уншиж, зардлыг автоматаар бүртгэнэ.",
        manualEntryTitle: "Гараар бүртгэх",
        newCategory: "Шинэ ангилал",
        categoryName: "Ангиллын нэр",
        createCategory: "Ангилал үүсгэх",
        merchantDetails: "Гүйлгээний мэдээлэл",
        amountAndCurrency: "Дүн & Валют",
        establishmentName: "Байгууллагын нэр",
        date: "Огноо",
        syncToHistory: "Түүх рүү хадгалах",
        upload: "Зураг оруулах",
        camera: "Камер",
        manual: "Гараар",
        // AI Hub Features
        aiHubTitle: "AI Hub",
        aiHubSubtitle: "Ухаалаг төв",
        aiHubEngineReady: "AI Engine бэлэн",
        aiHubStartJourney: "Шинэ аялал эхлүүлэх",
        aiHubUsageMonitoring: "Ашиглалтын хяналт",
        aiHubGoPro: "Pro болох",
        aiHubPlans: "Төлөвлөгөө",
        aiHubAnalytics: "Аналитик",
        aiHubAssets: "Ассет",
        aiFeaturePlannerTitle: "Аялал Төлөвлөгч",
        aiFeaturePlannerDesc: "Маршрут болон төлөвлөгөө боловсруулах",
        aiFeatureTransitTitle: "Нийтийн Тээвэр",
        aiFeatureTransitDesc: "Цэвэрхэн, хялбар замын хөтөч",
        aiFeatureTranslatorTitle: "Орчуулагч",
        aiFeatureTranslatorDesc: "Дуут болон бичгэн орчуулга",
        aiFeaturePosterTitle: "Аялалын Дурсамж",
        aiFeaturePosterDesc: "Зургийг арт болгож хувиргах",
        aiFeatureExpenseTitle: "Зардал Хөтлөгч",
        aiFeatureExpenseDesc: "Аялалын зардлаа хялбар удирдах",
        aiFeatureMedicalTitle: "Эмчилгээний Туслах",
        aiFeatureMedicalDesc: "Эмнэлэг хайх, шинж тэмдэг тайлбарлах",
        aiStatusReading: "Мэдээлэл уншиж байна...",
        aiStaffNotFound: "Ажилтан олдсонгүй",
        aiStaffStart: "Захирал аа, эхлүүлцгээе!",
        confirmDelete: "Та устгахдаа итгэлтэй байна уу?",
        confirmDeleteEsims: "{count} багцыг түүхээс устгах уу?",
        // Admin AI Staff
        adminAiStaffTitle: "AI Ажилчдын удирдлага",
        adminAiStaffSubtitle: "ДИЖИТАЛ ОФФИС",
        adminLoadDefaults: "Ажилчдыг ачаалах",
        adminAddNew: "Шинэ дүр нэмэх",
        adminSearchStaff: "Ажилтан хайх...",
        adminRoles: "Үүргүүд",
        adminSales: "Борлуулалт",
        adminTravel: "Аялал",
        adminManager: "Менежер",
        adminActive: "Идэвхтэй",
        adminInactive: "Идэвхгүй",
        adminSetDefault: "Үндсэн болгох",
        adminDefault: "Үндсэн",
        adminAllStaff: "Бүх ажилчид",
        adminStaffPermissionDenied: "Хандах эрх хүрэлцэхгүй байна. Firebase Rules-ээ шинэчилнэ үү.",
        adminHomeAdvisor: "Зөвлөх (Нүүр)",
        adminHubSpecialist: "Мэргэжилтэн (Hub)",
        adminOfficeManager: "Оффис Менежер",
        adminHomeSales: "HOME SALES",
        adminHubGuide: "HUB GUIDE",
        adminExpert: "GateSIM Экперт",
        // Inner AI Pages
        backToHub: "AI Hub руу буцах",
        // Budget
        budgetTitle: "Төсөв",
        budgetSubtitle: "AI Зардлын хяналт",
        totalSpent: "Нийт зарцуулсан",
        recentExpenses: "Сүүлийн түүх",
        itemsCount: "{count} бичиг баримт",
        noHistoryFound: "Түүх олдсонгүй",
        tapToScan: "Энд дарж баримт уншуулна уу",
        expenseLabel: "ЗАРДАЛ",
        // Medical
        medicalTravelTitle: "Эмчилгээний Аялал",
        medicalTravelSubtitle: "Солонгос, Тайланд, Турк, Энэтхэг",
        medicalDestinationsTitle: "Эмчилгээний аялалын улсууд",
        treatmentTypeTitle: "Эмчилгээний төрөл",
        additionalInfoOptional: "Нэмэлт мэдээлэл (заавал биш)",
        additionalInfoPlaceholder: "Жишээ: Солонгос руу мэс засалд орох, тусгай шаардлага...",
        generateMedicalPlanBtn: "Эмчилгээний аяллын төлөвлөгөө үүсгэх",
        medicalTripSummary: "Эмчилгээний Аялал",
        dayPlanCount: "{count} хоногийн төлөвлөгөө",
        hospitalInfoLabel: "Эмнэлгийн мэдээлэл",
        preTripChecklistLabel: "Урьдчилсан бэлтгэл",
        activitiesCount: "{count} үйл ажиллагаа",
        recoveryLabel: "Нөхөн сэргэлт",
        // Transit
        transitGuideTitle: "Нийтийн Тээврийн Хөтөч",
        transitGuideSubtitle: "Хамгийн дөт, хямд замыг олоорой",
        transitGreetingDefault: "Сайн байна уу? Би таны Нийтийн Тээврийн туслах байна. Та хаашаа явах вэ?",
        transitGreetingItinerary: "Таны төлөвлөгөөнд байгаа \"{location}\" руу хүрэх замыг зааж өгөх үү?",
        transitGreetingDestination: "Таны \"{destination}\" аяллын замд туслах уу?",
        nearestStationAction: "Ойрхон буудал",
        nearestStationQuery: "Хамгийн ойр автобусны буудал хаана байна?",
        toHospitalAction: "Эмнэлэг рүү",
        toHospitalQuery: "Хамгийн ойр эмнэлэг рүү яаж очих вэ?",
        subwayMapAction: "Метроны зураг",
        subwayMapQuery: "Метроны зураг харуулна уу",
        // Travel Memory
        memoryArtTitle: "Аяллын Дурсамж",
        memoryArtSubtitle: "Зургийг арт болгож хувиргах",
        uploadPhotoTitle: "Зураг хуулах",
        uploadPhotoDesc: "Төхөөрөмжөөс сонгох",
        takePhotoTitle: "Зураг дарах",
        takePhotoDesc: "Камер нээх",
        aiEnhanceBtn: "AI-р сайжруулах",
        filterLabel: "Шүүлтүүр",
        addTextTitle: "Текст нэмэх",
        titlePlaceholder: "Гарчиг...",
        locationPlaceholder: "📍 Байршил",
        datePlaceholder: "📅 Огноо",
        textPosBottom: "Доод",
        textPosTop: "Дээд",
        textPosCenter: "Төв",
        downloadBtn: "Татах",
        shareBtn: "Хуваалцах",
        // Translator
        translatorTitle: "Орчуулга",
        translatorTextMode: "Текст",
        translatorVoiceMode: "Дуу",
        translatorCameraMode: "Камер",
        translatorInputLabel: "Оролт",
        translatorOutputLabel: "Гаралт",
        translatorPlaceholder: "Орчуулах текстээ бичнэ үү...",
        translatorBtn: "Орчуулах",
        translationFailed: "Орчуулга амжилтгүй",
        // Travel Planner
        plannerTitle: "Аялал Төлөвлөгч",
        plannerSubtitle: "AI-р төгс аяллын төлөвлөгөө гаргах",
        plannerStep1: "Үндсэн",
        plannerStep2: "Зорилго",
        plannerStep3: "Маршрут",
        plannerStep4: "Нээлт",
        plannerStep5: "Төлөвлөгөө",
        plannerNext: "Дараах",
        plannerBack: "Буцах",
        plannerDuration: "Хэдэн хоног?",
        plannerBudget: "Төсөв",
        plannerTravelers: "Аялагчид",
        plannerAdults: "Насанд хүрэгчид",
        plannerChildren: "Хүүхэд",
        plannerTarget: "Хаашаа?",
        plannerStartDate: "Хэзээ?",
        plannerPurposes: "Аяллын төрөл",
        plannerDiscovery: "Нээлт",
        plannerGenerate: "Төлөвлөгөө гаргах",
        plannerGenerating: "Төлөвлөж байна...",
        plannerAnalyzing: "Аяллын мэдээллийг боловсруулж байна...",
        plannerFinding: "Хамгийн тохиромжтой нислэгүүдийг хайж байна...",
        plannerCurating: "Зочид буудал болон байршлуудыг шалгаж байна...",
        plannerFinalizing: "Таны төгс аяллын хөтөлбөрийг эцэслэн гаргаж байна...",
        plannerSaveTrip: "Аялал хадгалах",
        plannerSaved: "Аялал хадгалагдлаа",
        plannerSuggestCities: "Хот санал болгох",
        plannerAddCustomCity: "Өөр хот нэмэх",
        plannerSelectedHotels: "Сонгосон буудлууд",
        plannerItinerary: "Аяллын маршрут",
        plannerDailyPlan: "Өдрийн төлөвлөгөө",
        plannerStep1Header: "1. Улс болон хугацаагаа сонгох",
        plannerStep2Header: "2. Аяллын зорилго, тээврээ тодорхойлох",
        plannerDestinationLabel: "Очих улс",
        plannerSelectCountry: "Улс сонгоно уу",
        plannerDateLabel: "Аялах огноо",
        plannerPickDate: "Огноо сонгох",
        plannerDurationLabel: "Хонох өдөр",
        plannerTotalDays: "Нийт хоног",
        plannerChinaDistance: "Хилээс очих зай",
        plannerNear: "Ойр",
        plannerNearDesc: "Эрээн, Хөх хот...",
        plannerMid: "Дунд",
        plannerMidDesc: "Бээжин, Тяньжин...",
        plannerFar: "Хол",
        plannerFarDesc: "Шанхай, Гуанжу...",
        plannerSuggestNote: "* Сонголт бүрд тохирсон хотууд санал болгоно",
        plannerTravelerAdult: "Том хүн",
        plannerTravelerChild: "Хүүхэд",
        plannerTravelerNote: "* Зардлын тооцоололд аялагчдын тоо шууд нөлөөлнө",
        plannerContinue: "Үргэлжлүүлэх",
        plannerPurposeLabel: "Аяллын зорилго",
        plannerTransportLabel: "Тээврийн сонголт",
        plannerTransportNote: "* Таны аяллын төлөвлөгөө эдгээр сонголтуудад тулгуурлан боловсрогдоно",
        plannerTransportFlight: "Онгоц",
        plannerTransportTrain: "Галт тэрэг",
        plannerTransportBus: "Автобус",
        plannerTransportMetro: "Метро",
        plannerTransportTaxi: "Такси",
        plannerInternational: "Улс хооронд",
        plannerIntercity: "Хот хооронд",
        plannerInnerCity: "Хот дотор",
        plannerSelectFlight: "Нислэг сонгох",
        plannerSearchingFlights: "Танд тохирох нислэг хайж байна...",
        plannerFindFlights: "Нислэг хайх",
        plannerFlightDirect: "Шууд",
        plannerFlightStops: "{count} дамжлага",
        plannerFlightRefresh: "Дахин хайх",
        plannerNeedsPlaceholder: "Таны тусгай хэрэгцээ...",
        plannerNeedsSuffix: "хэрэгцээ",
        plannerStep3Header: "3. Аяллын маршрут, хотуудаа төлөвлөх",
        plannerStep4Header: "4. Зочид буудал, байрлах газраа сонгох",
        plannerAISuggestedCities: "AI-ийн санал болгож буй хотууд",
        plannerAddCity: "Хот нэмэх",
        plannerOtherCity: "Өөр хот...",
        plannerEnterCity: "Хот оруулах",
        plannerCityNameQuery: "Хотын нэр?",
        plannerTripSequence: "Аяллын дараалал",
        plannerStart: "Эхлэл",
        plannerDest: "Очих",
        plannerBudgetLevel: "Төсөв",
        plannerBudgetCheap: "Хэмнэлттэй",
        plannerBudgetEconomy: "Дундаж",
        plannerBudgetLuxury: "Люкс",
        plannerAdd: "Нэмэх",
        plannerChange: "Солих",
        plannerSelect: "Сонгох",
        plannerRemove: "Устгах",
        plannerYourFlight: "Таны нислэг",
        plannerStep5Header: "5. Үзэх газрууд, үйл ажиллагаагаа сонгох",
        plannerAIRecommendationNote: "AI-аар таны сонирхолд 100% нийцүүлэн бэлтгэв",
        plannerFilter: "Шүүлтүүр",
        plannerSort: "Эрэмбэлэх",
        plannerAllHotels: "Бүгд",
        plannerLiveData: "✅ Бодит (Live)",
        plannerStars4: "⭐️ 4+ Одтой",
        plannerRecommended: "Санал болгож буй",
        plannerPriceLowToHigh: "Үнэ (Бага -> Их)",
        plannerPriceHighToLow: "Үнэ (Их -> Бага)",
        plannerRatingHigh: "Үнэлгээ (Өндөр)",
        plannerResultsFound: "илэрц",
        plannerMyChoice: "Өөрийн сонголт",
        plannerMyChoiceDesc: "Би энэ хотод өөрийн буудалд байрлана.",
        plannerMyChoiceStayDesc: "Санал болгосон буудлыг сонгох шаардлагагүй. Би өөрөө буудлаа шийднэ.",
        plannerFlexible: "Уян хатан",
        plannerViewDetails: "Дэлгэрэнгүй харах",
        plannerSkip: "Алгасах",
        plannerGeneratePlan: "Төлөвлөгөө гаргах",
        plannerWaitMoment: "Түр хүлээнэ үү...",
        plannerFreeTime: "Өөрийн сонголт / Чөлөөт цаг",
        plannerFreeTimeDesc: "Төлөвлөгөөнд тусгай үзвэр оруулахгүй, өөрийнхөөрөө аялах",
        plannerDecideLater: "Төлөвлөгөөнд тусгай үзвэр оруулахгүй, чөлөөтэй явах",
        // Trip Purposes
        purposeTourist: "Жуулчлал",
        purposeTouristDesc: "Ерөнхий үзвэрүүд, алдартай газрууд",
        purposeRelaxation: "Амралт",
        purposeRelaxationDesc: "Алжаал тайлах, спа, сувилал",
        purposeAdventure: "Адал явдал",
        purposeAdventureDesc: "Экстрим спорт, идэвхтэй хөдөлгөөн",
        purposeFamily: "Гэр бүл",
        purposeFamilyDesc: "Хүүхдэд ээлтэй, аюулгүй газрууд",
        purposeRomantic: "Романтик",
        purposeRomanticDesc: "Хосуудад зориулсан тусгай газрууд",
        purposeCulture: "Соёл",
        purposeCultureDesc: "Музей, түүхэн дурсгалт газрууд",
        purposeShopping: "Шопинг",
        purposeShoppingDesc: "Худалдааны төвүүд, захууд",
        purposeFoodie: "Хоол аялал",
        purposeFoodieDesc: "Ресторан, хоолны туршлагууд",
        purposeProcurement: "Бараа таталт",
        purposeProcurementDesc: "Бөөний төвүүд, бараа бэлтгэл, үйлдвэр",
        purposeBusiness: "Бизнес",
        purposeBusinessDesc: "Уулзалт, ажил хэргийн хэрэгцээ",
        purposeMedical: "Эмчилгээ",
        purposeMedicalDesc: "Эрүүл мэнд, оношилгоо, сувилгаа",
        purposeEducation: "Боловсрол",
        purposeEducationDesc: "Сургууль, сургалт, сургалтын аялал",
        purposeEvent: "Арга хэмжээ",
        purposeEventDesc: "Концерт, наадам, фестиваль",
        plannerLoginRequired: "Төлөвлөгөөг хадгалахын тулд нэвтэрнэ үү",
        plannerSaveSuccess: "Амжилттай хадгалагдлаа! Та өөрийн профайлаас үзэх боломжтой.",
        plannerSaveFail: "Хадгалахад алдаа гарлаа.",
        plannerPrintFail: "Хэвлэх боломжгүй байна. Та дэлгэцийн зураг авна уу.",
        plannerShareTitle: "Аяллын Төлөвлөгөө",
        plannerShareText: "Миний {dest} руу хийх аяллын төлөвлөгөөг үзээрэй!",
        plannerLinkCopied: "Холбоос хуулагдлаа!",
        plannerShareFail: "Хуваалцах боломжгүй байна. Дэлгэцийн зураг авна уу.",
        plannerDestinationAlert: "Destination сонгоно уу",
        plannerPurposeAlert: "Аяллын зорилго сонгоно уу",
        plannerCityAlert: "Хот сонгоно уу",
        plannerItineraryReady: "Төгс хөтөлбөр бэлэн боллоо",
        plannerDurLabel: "Хугацаа",
        plannerActivitiesCount: "үйл ажиллагаа",
        plannerBudgetCalc: "Зардлын тооцоолол",
        plannerSavePlan: "Төлөвлөгөө хадгалах",
        plannerDownloadPDF: "PDF Татах",
        plannerAIInsight: "AI Танилцуулга",
        plannerGatheringInsights: "Мэдээлэл цуглуулж байна...",
        plannerAIProcessing: "AI мэдээлэл боловсруулж байна",
        plannerOverview: "Тойм мэдээлэл",
        plannerHighlights: "Онцлох зүйлс",
        plannerProTips: "Pro Зөвлөмж",
        plannerCultureEttiquette: "Соёл ба уламжлал",
        plannerNoInsights: "Мэдээлэл олдсонгүй.",
        plannerClose: "Хаах",
        plannerGotIt: "Ойлголоо",
        plannerTravelersLabel: "Аялагчид",
        wizardDestQuestion: "Хаашаа явахаар төлөвлөж байна?",
        wizardDestPlaceholder: "Хотын нэр...",
        wizardDurQuestion: "Хэд хоног аялах вэ?",
        wizardDurPlaceholder: "Хоногийн тоо...",
        wizardPurposeQuestion: "Аяллын үндсэн зорилго юу вэ?",
    },
    en: {
        home: "Home",
        packages: "Packages",
        myEsims: "My eSIM",
        profile: "Profile",
        myProfile: "My Profile",
        user: "User",
        login: "Login",
        greeting: "Hello",
        logout: "Logout",
        save: "Save",
        saving: "Saving...",
        appearance: "Appearance",
        lightMode: "Light",
        darkMode: "Dark",
        email: "Email Address",
        phone: "Phone Number",
        phonePlaceholder: "Enter your phone number",
        back: "Back",
        loading: "Loading...",
        error: "An error occurred",
        success: "Success",
        eSimPlatform: "eSIM Platform",
        // Auth
        welcomeBack: "Welcome Back",
        signUp: "Sign Up",
        authSubtitle: "Join GateSIM and connect anywhere in the world",
        continueWithGoogle: "Continue with Google",
        or: "or",
        password: "Password",
        noAccount: "Don't have an account?",
        alreadyRegistered: "Already registered?",
        phoneOptional: "Phone Number (Optional)",
        continueWithEmail: "Continue with Email",
        magicLinkSubtitle: "We will send you a temporary login link to your email",
        emailPlaceholder: "Your email address",
        magicLinkSent: "Login link sent. Please check your email.",
        forgotPassword: "Forgot Password?",
        forgotPasswordDesc: "Enter your registered email to receive a reset link",
        sendResetLink: "Send Reset Link",
        resetEmailSent: "Email Sent",
        resetEmailSentDesc: "A password reset link has been sent to your email.",
        backToLogin: "Back to Login",
        // Filters
        duration1_7: "1-7 Days",
        duration8_15: "8-15 Days",
        duration15Plus: "15+ Days",
        packagesFound: "Total {count} packages found",
        countryEsimPackages: "{country} eSIM Packages",
        all: "All",
        unlimited: "Unlimited",
        noPackagesMatch: "No packages match the selected filters.",
        clearFilters: "Clear Filters",
        allCountries: "All Countries",
        searchPackagesPlaceholder: "Search countries, packages...",
        countPackages: "{count} packages",
        noPackagesFound: "No packages found",
        noPackagesDesc: "Try changing your search or filters.",
        loadingMore: "Loading...",
        scrollMore: "Scroll down for more",
        allPackagesShown: "All {count} packages shown ✓",
        // Nav
        navHome: "Home",
        navPackages: "Packages",
        navMyEsim: "My eSIM",
        navProfile: "Profile",
        // AI Chat
        aiTitle: "AI Assistant",
        aiDescription: "Smart Advisor",
        aiGuestMode: "Guest Mode (eSIM only)",
        aiThinking: "Thinking...",
        aiPlaceholder: "What package are you looking for?",
        aiPopularPackages: "Popular Searches:",
        aiSeeAll: "See all packages",
        aiCompatibilityWarning: "Hello! Your {device} might not support eSIM. ⚠️\n\nPlease check compatibility before purchasing.",
        aiGreeting1: "Hello! Where are you traveling to, and for how long? 🌍✈️",
        aiGreeting2: "Hello! Can I help you find a suitable eSIM package for your trip? 🗺️✨",
        aiGreeting3: "Hi! Where's your next trip? I can find the best package for you. 🚀",
        aiGreeting4: "Hello! Tell me which country you're traveling to, and I'll show you the best packages. 💡",
        // Home
        homeHeroTitle: "Connectivity Everywhere",
        homeHeroSubtitle: "Your Global Gateway",
        homeHeroDesc: "Connect to the internet in 200+ countries at the most affordable prices.",
        homeSearchPlaceholder: "Where are you going?",
        homeDuration7: "7 Days",
        homeDuration15: "15 Days",
        homePopularTitle: "Popular Countries",
        homeFeaturedTitle: "Featured Packages",
        homeAiAssistantTitle: "Smart Travel Assistant 🤖",
        homeAiAssistantDesc: "Just tell me where you're going, and I'll recommend the best package for you.",
        homeAiAssistantExample: "Try: \"Japan for 2 weeks\"",
        homeAiFeature1: "💬 Multilingual",
        homeAiFeature2: "⚡ Instant Response",
        homeAiFeature3: "🎯 Personalized Advice",
        day: "days",
        viewPackages: "View Packages",
        homeAiExample1: "Japan 2 weeks",
        homeAiExample2: "Korea 10 GB",
        plusCountries: "+ {count} countries",
        myEsimsHeroTitle: "My eSIMs",
        myEsimsHeroDesc: "Manage your purchased packages here",
        active: "Active",
        history: "History",
        loginRequired: "Login Required",
        loginRequiredDesc: "Please login to view your orders.",
        noActiveEsims: "No active eSIMs",
        noActiveEsimsDesc: "Choose an eSIM package and start your journey.",
        noHistory: "History is empty",
        noHistoryDesc: "Your purchase history will appear here.",
        selectPackage: "Select Package",
        statusActive: "Active",
        statusPending: "Pending",
        statusCompleted: "Completed",
        dataUsage: "Data Usage",
        daysRemaining: "{count} days remaining",
        select: "Select",
        cancel: "Cancel",
        selectAll: "Select All",
        delete: "Delete",
        esimDetails: "eSIM Details",
        qrScanInstructions: "Scan the QR code below to activate your eSIM",
        downloadQr: "Download QR (Image)",
        download: "Download",
        qrOneTime: "Code can only be scanned once",
        manualEntry: "Manual Entry Code",
        iccid: "ICCID (Serial Number)",
        sendToFriend: "Send to Friend",
        installationGuide: "View Installation Guide",
        featured: "Featured",
        regional: "Regional",
        vpnIncluded: "VPN Included",
        topUp: "Top-up",
        newEsim: "New eSIM",
        topUpDesc: "For existing eSIM users only",
        topUpNoEsimError: "You don't have an active eSIM to top up",
        topUpLoginRequired: "You must be logged in to purchase a top-up.",
        topUpProviderError: "This can only top up {provider} eSIMs",
        incompatible: "Incompatible",
        vpnFeatureTitle: "VPN Included - Unrestricted Access",
        vpnFeatureDesc: "Freely access blocked services like Facebook, Instagram, Youtube, and Google without any restrictions.",
        newPackagesBannerTitle: "Get New eSIM",
        newPackagesBannerDesc: "Get travel data in over 200 countries at the most affordable prices.",
        topUpPackagesBannerTitle: "Top-up eSIM",
        topUpPackagesBannerDesc: "Top up your active GateSIM eSIM with unlimited high-speed data.",
        price: "Price",
        validity: "Validity",
        coverage: "Coverage",
        activation: "Activation",
        instant: "Instant",
        packageDetails: "Package Details",
        compatibleDevices: "Compatible Devices",
        importantNotes: "Important Notes",
        totalAmount: "Total Amount",
        buyNow: "Buy Now",
        checkoutTitle: "Checkout",
        receiveEmail: "Contact Email",
        invalidEmail: "Invalid email format",
        emailNote: "QR code will be sent to this email",
        paymentMethod: "Payment Method",
        qpayDesc: "Pay with Banking App",
        internationalCard: "International Card",
        comingSoon: "Coming Soon",
        payNow: "Pay Now",
        paymentSuccess: "Payment Success!",
        preparingEsim: "Preparing your eSIM...",
        orderConfirmed: "Your order is confirmed. Please check your email.",
        orderNumber: "Order Number",
        backToHome: "Back to Home",
        checkPayment: "Check Payment",
        waitingPayment: "Waiting for payment...",
        bankAppPay: "Pay with Bank App",
        summary: "Summary",
        package: "Package",
        // Technical Info
        speed4G5G: "4G/5G High Speed Network",
        noSpeedLimit: "No Speed Limit (High Speed)",
        hotspotSupport: "Hotspot/Tethering Supported",
        activationOnUse: "Validity starts upon first connection",
        emailDeliveryInfo: "eSIM QR code will be saved in 'My eSIMs' (for logged-in users) and sent to your email within 1-5 minutes. Ensure your device is eSIM compatible.",
        // Country Names
        country_JP: "Japan",
        country_KR: "South Korea",
        country_CN: "China",
        country_TH: "Thailand",
        country_SG: "Singapore",
        country_VN: "Vietnam",
        country_TR: "Turkey",
        country_US: "USA",
        country_RU: "Russia",
        country_KZ: "Kazakhstan",
        country_DE: "Germany",
        country_FR: "France",
        country_IT: "Italy",
        country_ES: "Spain",
        country_NL: "Netherlands",
        country_GB: "United Kingdom",
        country_EU: "Europe",
        country_AL: "Albania",
        country_AE: "United Arab Emirates",
        country_HK: "Hong Kong",
        country_TW: "Taiwan",
        // Device Names
        devicePhone: "Phone",
        yourPhone: "Your Phone",
        compatibleIphone: "iPhone XR, XS, 11, 12, 13, 14, 15, 16 and newer models. \n⚠️ Warning: Most iPhones purchased in China, Hong Kong, or Macau (e.g. XS, 11, 12, 13...) do NOT support eSIM (Physical Dual SIM only).",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold series. \n⚠️ Warning: Models from China, Hong Kong, and Macau typically do NOT support eSIM.",
        compatiblePixel: "Google Pixel 3, 3XL, 4, 4XL, 5... and all newer models.",
        // Expense Tracker
        aiScanReceipt: "Scan Receipt",
        aiScanDesc: "AI will analyze your receipt and track expenses automatically.",
        manualEntryTitle: "Manual Entry",
        newCategory: "New Category",
        categoryName: "Category Name",
        createCategory: "Create Category",
        merchantDetails: "Merchant Details",
        amountAndCurrency: "Amount & Currency",
        establishmentName: "Establishment Name",
        date: "Date",
        syncToHistory: "Sync to History",
        upload: "Upload",
        camera: "Camera",
        manual: "Manual",
        // AI Hub Features
        aiHubTitle: "AI Hub",
        aiHubSubtitle: "Intelligence Center",
        aiHubEngineReady: "AI Engine Ready",
        aiHubStartJourney: "Start New Journey",
        aiHubUsageMonitoring: "Usage Monitoring",
        aiHubGoPro: "Go Pro",
        aiHubPlans: "Plans",
        aiHubAnalytics: "Analytics",
        aiHubAssets: "Assets",
        aiFeaturePlannerTitle: "Trip Planner",
        aiFeaturePlannerDesc: "Smart itinerary and route planning",
        aiFeatureTransitTitle: "Transit Guide",
        aiFeatureTransitDesc: "Seamless navigation with AI",
        aiFeatureTranslatorTitle: "Translator",
        aiFeatureTranslatorDesc: "Voice and text translation",
        aiFeaturePosterTitle: "Memory Art",
        aiFeaturePosterDesc: "Turn photos into AI art",
        aiFeatureExpenseTitle: "Expense Tracker",
        aiFeatureExpenseDesc: "Smart travel expense management",
        aiFeatureMedicalTitle: "Medical Assistant",
        aiFeatureMedicalDesc: "Find clinics and explain symptoms",
        aiStatusReading: "Reading data...",
        aiStaffNotFound: "No staff found",
        aiStaffStart: "Let's get started!",
        confirmDelete: "Are you sure you want to delete?",
        confirmDeleteEsims: "Delete {count} packages from history?",
        // Admin AI Staff
        adminAiStaffTitle: "AI Staff Management",
        adminAiStaffSubtitle: "DIGITAL OFFICE",
        adminLoadDefaults: "Load Staff",
        adminAddNew: "Add New Role",
        adminSearchStaff: "Search Staff...",
        adminRoles: "Roles",
        adminSales: "Sales",
        adminTravel: "Travel",
        adminManager: "Manager",
        adminActive: "Active",
        adminInactive: "Inactive",
        adminSetDefault: "Set as Default",
        adminDefault: "Default",
        adminAllStaff: "All Staff",
        adminStaffPermissionDenied: "Permission denied. Please check Firebase Rules.",
        adminHomeAdvisor: "Home Advisor",
        adminHubSpecialist: "Hub Specialist",
        adminOfficeManager: "Office Manager",
        adminHomeSales: "HOME SALES",
        adminHubGuide: "HUB GUIDE",
        adminExpert: "GateSIM Expert",
        // Inner AI Pages
        backToHub: "Back to Hub",
        // Budget
        budgetTitle: "Budget",
        budgetSubtitle: "AI Expense Control",
        totalSpent: "Total Spent",
        recentExpenses: "Recent History",
        itemsCount: "{count} ITEMS",
        noHistoryFound: "No history found",
        tapToScan: "Tap to scan a receipt",
        expenseLabel: "EXPENSE",
        // Medical
        medicalTravelTitle: "Medical Travel",
        medicalTravelSubtitle: "Korea, Thailand, Turkey, India",
        medicalDestinationsTitle: "Medical Tourism Destinations",
        treatmentTypeTitle: "Treatment Type",
        additionalInfoOptional: "Additional Info (optional)",
        additionalInfoPlaceholder: "Example: Surgery in Korea, specific requirements...",
        generateMedicalPlanBtn: "Generate Medical Trip Plan",
        medicalTripSummary: "Medical Trip",
        dayPlanCount: "{count} day plan",
        hospitalInfoLabel: "Hospital Information",
        preTripChecklistLabel: "Pre-Trip Checklist",
        activitiesCount: "{count} activities",
        recoveryLabel: "Recovery",
        // Transit
        transitGuideTitle: "Transit Guide",
        transitGuideSubtitle: "Find the fastest and cheapest routes",
        transitGreetingDefault: "Hello, I'm your Transit Assistant. Where would you like to go?",
        transitGreetingItinerary: "Should I guide you to \"{location}\" from your itinerary?",
        transitGreetingDestination: "Need help getting around in \"{destination}\"?",
        nearestStationAction: "Nearest Station",
        nearestStationQuery: "Where is the nearest bus/train station?",
        toHospitalAction: "To Hospital",
        toHospitalQuery: "How do I get to the nearest hospital?",
        subwayMapAction: "Subway Map",
        subwayMapQuery: "Show me the subway map",
        // Travel Memory
        memoryArtTitle: "Memory Art",
        memoryArtSubtitle: "Turn photo into poster",
        uploadPhotoTitle: "Upload Photo",
        uploadPhotoDesc: "Choose from device",
        takePhotoTitle: "Take Photo",
        takePhotoDesc: "Open camera",
        aiEnhanceBtn: "AI Enhance",
        filterLabel: "Filter",
        addTextTitle: "Add Text",
        titlePlaceholder: "Title...",
        locationPlaceholder: "📍 Location",
        datePlaceholder: "📅 Date",
        textPosBottom: "Bottom",
        textPosTop: "Top",
        textPosCenter: "Center",
        downloadBtn: "Download",
        shareBtn: "Share",
        // Translator
        translatorTitle: "Translator",
        translatorTextMode: "Text",
        translatorVoiceMode: "Voice",
        translatorCameraMode: "Camera",
        translatorInputLabel: "Input",
        translatorOutputLabel: "Output",
        translatorPlaceholder: "Enter text to translate...",
        translatorBtn: "Translate",
        translationFailed: "Translation failed",
        // Travel Planner
        plannerTitle: "Travel Planner",
        plannerSubtitle: "AI-crafted perfect itinerary",
        plannerStep1: "Basics",
        plannerStep2: "Purpose",
        plannerStep3: "Route",
        plannerStep4: "Discovery",
        plannerStep5: "Itinerary",
        plannerNext: "Next",
        plannerBack: "Back",
        plannerDuration: "How many days?",
        plannerBudget: "Budget",
        plannerTravelers: "Travelers",
        plannerAdults: "Adults",
        plannerChildren: "Children",
        plannerTarget: "Where to?",
        plannerStartDate: "When?",
        plannerPurposes: "Trip Purpose",
        plannerDiscovery: "Discovery",
        plannerGenerate: "Generate Itinerary",
        plannerGenerating: "Planning...",
        plannerAnalyzing: "Analyzing travel preferences...",
        plannerFinding: "Finding the best routes and flights...",
        plannerCurating: "Curating top-rated hotels and spots...",
        plannerFinalizing: "Finalizing your perfect itinerary...",
        plannerSaveTrip: "Save Trip",
        plannerSaved: "Trip Saved",
        plannerSuggestCities: "Suggest Cities",
        plannerAddCustomCity: "Add Custom City",
        plannerSelectedHotels: "Selected Hotels",
        plannerItinerary: "Travel Itinerary",
        plannerDailyPlan: "Daily Plan",
        plannerStep1Header: "1. Select Destination & Duration",
        plannerStep2Header: "2. Define Purpose & Transport",
        plannerDestinationLabel: "Destination",
        plannerSelectCountry: "Select Country",
        plannerDateLabel: "Travel Date",
        plannerPickDate: "Pick a date",
        plannerDurationLabel: "Duration",
        plannerTotalDays: "Total Days",
        plannerChinaDistance: "Distance from Border",
        plannerNear: "Near",
        plannerNearDesc: "Erenhot, Hohhot...",
        plannerMid: "Mid",
        plannerMidDesc: "Beijing, Tianjin...",
        plannerFar: "Far",
        plannerFarDesc: "Shanghai, Guangzhou...",
        plannerSuggestNote: "* Cities will be suggested based on your choices",
        plannerTravelerAdult: "Adults",
        plannerTravelerChild: "Children",
        plannerTravelerNote: "* Budget will be calculated based on the number of travelers",
        plannerContinue: "Continue",
        plannerPurposeLabel: "Trip Purposes",
        plannerTransportLabel: "Transport Selection",
        plannerTransportNote: "* Your itinerary will be tailored based on these choices",
        plannerTransportFlight: "Flight",
        plannerTransportTrain: "Train",
        plannerTransportBus: "Bus",
        plannerTransportMetro: "Metro",
        plannerTransportTaxi: "Taxi",
        plannerInternational: "International",
        plannerIntercity: "Intercity",
        plannerInnerCity: "Inner City",
        plannerSelectFlight: "Select Flight",
        plannerSearchingFlights: "Searching best flights for you...",
        plannerFindFlights: "Find Flights",
        plannerFlightDirect: "Direct",
        plannerFlightStops: "{count} stops",
        plannerFlightRefresh: "Refresh",
        plannerNeedsPlaceholder: "Enter your special needs...",
        plannerNeedsSuffix: "Needs",
        plannerStep3Header: "3. Plan Your Route & Cities",
        plannerStep4Header: "4. Choose Hotels & Accommodation",
        plannerAISuggestedCities: "AI Suggested Cities",
        plannerAddCity: "Add City",
        plannerOtherCity: "Other city...",
        plannerEnterCity: "Enter City",
        plannerCityNameQuery: "City Name?",
        plannerTripSequence: "Trip Sequence",
        plannerStart: "Start",
        plannerDest: "Dest",
        plannerBudgetLevel: "Budget",
        plannerBudgetCheap: "Budget",
        plannerBudgetEconomy: "Economy",
        plannerBudgetLuxury: "Luxury",
        plannerAdd: "Add",
        plannerChange: "Change",
        plannerSelect: "Select",
        plannerRemove: "Remove",
        plannerYourFlight: "Your Flight",
        plannerStep5Header: "5. Select Activities & Experiences",
        plannerAIRecommendationNote: "AI-curated matching your travel goals 100%",
        plannerFilter: "Filter By",
        plannerSort: "Sort By",
        plannerAllHotels: "All Hotels",
        plannerLiveData: "✅ Live Data Only",
        plannerStars4: "⭐️ 4+ Stars",
        plannerRecommended: "Recommended",
        plannerPriceLowToHigh: "Price: Low to High",
        plannerPriceHighToLow: "Price: High to Low",
        plannerRatingHigh: "Rating: High to Low",
        plannerResultsFound: "results found",
        plannerMyChoice: "My own choice",
        plannerMyChoiceDesc: "I will arrange my own accommodation in this city.",
        plannerMyChoiceStayDesc: "No need to pick from suggestions. I will handle my own stay.",
        plannerFlexible: "Flexible",
        plannerViewDetails: "View Details",
        plannerSkip: "Skip",
        plannerGeneratePlan: "Generate Plan",
        plannerWaitMoment: "Please wait a moment...",
        plannerFreeTime: "My choice / Free time",
        plannerFreeTimeDesc: "No specific activities, I will explore on my own",
        plannerDecideLater: "I'll decide my activities later",
        // Trip Purposes
        purposeTourist: "Tourism",
        purposeTouristDesc: "General sightseeing and popular attractions",
        purposeRelaxation: "Relaxation",
        purposeRelaxationDesc: "Leisure, spa, and wellness",
        purposeAdventure: "Adventure",
        purposeAdventureDesc: "Active sports and thrilling activities",
        purposeFamily: "Family",
        purposeFamilyDesc: "Safe and fun spots for kids and adults",
        purposeRomantic: "Romantic",
        purposeRomanticDesc: "Special spots for couples and honeymoons",
        purposeCulture: "Culture",
        purposeCultureDesc: "History, museums and local heritage",
        purposeShopping: "Shopping",
        purposeShoppingDesc: "Malls, markets and boutiques",
        purposeFoodie: "Foodie",
        purposeFoodieDesc: "Fine dining and local specialties",
        purposeProcurement: "Procurement",
        purposeProcurementDesc: "Wholesale markets, sourcing, and factories",
        purposeBusiness: "Business",
        purposeBusinessDesc: "Work-related and professional events",
        purposeMedical: "Medical",
        purposeMedicalDesc: "Check-ups, treatments and recovery",
        purposeEducation: "Education",
        purposeEducationDesc: "Schools, courses and study tours",
        purposeEvent: "Event",
        purposeEventDesc: "Festivals, concerts and exhibitions",
        plannerLoginRequired: "Please login to save your trip",
        plannerSaveSuccess: "Successfully saved! You can view it in your profile.",
        plannerSaveFail: "Failed to save trip.",
        plannerPrintFail: "Printing is not supported on this device. Please take a screenshot.",
        plannerShareTitle: "Travel Itinerary",
        plannerShareText: "Check out my travel plan for {dest}!",
        plannerLinkCopied: "Link copied to clipboard!",
        plannerShareFail: "Unable to share. Please take a screenshot.",
        plannerDestinationAlert: "Please select a destination",
        plannerPurposeAlert: "Please select at least one purpose",
        plannerCityAlert: "Please select at least one city",
        plannerItineraryReady: "Perfect Itinerary Ready",
        plannerDurLabel: "Duration",
        plannerActivitiesCount: "activities",
        plannerBudgetCalc: "Budget Calculation",
        plannerSavePlan: "Save Plan",
        plannerDownloadPDF: "Download PDF",
        plannerAIInsight: "AI Insight",
        plannerGatheringInsights: "Gathering insights...",
        plannerAIProcessing: "AI is processing information",
        plannerOverview: "Overview",
        plannerHighlights: "Highlights",
        plannerProTips: "Pro Tips",
        plannerCultureEttiquette: "Culture & Ettiquette",
        plannerNoInsights: "No insights found.",
        plannerClose: "Close",
        plannerGotIt: "Got it",
        plannerTravelersLabel: "Travelers",
        wizardDestQuestion: "Where are you planning to go?",
        wizardDestPlaceholder: "City name...",
        wizardDurQuestion: "How many days is your trip?",
        wizardDurPlaceholder: "Number of days...",
        wizardPurposeQuestion: "What is the main purpose?",
    },
    cn: {
        home: "首页",
        packages: "套餐",
        myEsims: "我的eSIM",
        profile: "个人资料",
        myProfile: "我的资料",
        user: "用户",
        login: "登录",
        greeting: "你好",
        logout: "注销",
        save: "保存",
        saving: "正在保存...",
        appearance: "外观",
        lightMode: "日间",
        darkMode: "夜间",
        email: "电子邮箱",
        phone: "电话号码",
        phonePlaceholder: "输入您的电话号码",
        back: "返回",
        loading: "加载中...",
        error: "发生错误",
        success: "成功",
        eSimPlatform: "eSIM 平台",
        // Auth
        welcomeBack: "欢迎回来",
        signUp: "注册",
        authSubtitle: "加入 GateSIM，随时随地保持联系",
        continueWithGoogle: "使用 Google 继续",
        or: "或",
        password: "密码",
        noAccount: "还没有账户？",
        alreadyRegistered: "已经注册了？",
        phoneOptional: "电话号码 (可选)",
        continueWithEmail: "使用电子邮件继续",
        magicLinkSubtitle: "我们将向您的邮箱发送一个临时登录链接",
        emailPlaceholder: "您的电子邮箱地址",
        magicLinkSent: "登录链接已发送。请检查您的邮箱。",
        forgotPassword: "忘记密码？",
        forgotPasswordDesc: "输入您注册的邮箱以接收重置链接",
        sendResetLink: "发送重置链接",
        resetEmailSent: "邮件已发送",
        resetEmailSentDesc: "密码重置链接已发送到您的邮箱。",
        backToLogin: "返回登录",
        // Filters
        duration1_7: "1-7天",
        duration8_15: "8-15天",
        duration15Plus: "15+天",
        packagesFound: "共找到 {count} 个套餐",
        countryEsimPackages: "{country} eSIM 套餐",
        all: "全部",
        unlimited: "无限",
        noPackagesMatch: "没有符合所选过滤条件的套餐。",
        clearFilters: "清除筛选",
        allCountries: "所有国家",
        searchPackagesPlaceholder: "搜索国家或套餐...",
        countPackages: "{count} 个套餐",
        noPackagesFound: "未找到套餐",
        noPackagesDesc: "请尝试更改搜索或过滤器。",
        loadingMore: "加载中...",
        scrollMore: "向下滑动查看更多",
        allPackagesShown: "已显示全部 {count} 个套餐 ✓",
        // Nav
        navHome: "首页",
        navPackages: "套餐",
        navMyEsim: "我的eSIM",
        navProfile: "个人资料",
        // AI Chat
        aiTitle: "AI 助手",
        aiDescription: "智能建议",
        aiGuestMode: "游客模式 (仅限 eSIM)",
        aiThinking: "思考中...",
        aiPlaceholder: "您在寻找什么套餐？",
        aiPopularPackages: "热门套餐：",
        aiSeeAll: "查看所有套餐",
        aiCompatibilityWarning: "您好！您的 {device} 可能不支持 eSIM。⚠️\n\n请在购买前检查设备兼容性。",
        aiGreeting1: "您好！您要去哪里旅行，打算呆多久？🌍✈️",
        aiGreeting2: "您好！我可以帮您找到适合旅行的 eSIM 套餐吗？🗺️✨",
        aiGreeting3: "嗨！您的下一次旅行去哪里？我可以为您找到最合适的套餐。🚀",
        aiGreeting4: "您好！告诉我您要去哪个国家，我会为您推荐最合适的套餐。💡",
        // Home
        homeHeroTitle: "全球互联",
        homeHeroSubtitle: "您的全球门户",
        homeHeroDesc: "以最实惠的价格在 200 多个国家/地区连接互联网。",
        homeSearchPlaceholder: "您要去哪里？",
        homeDuration7: "7天",
        homeDuration15: "15天",
        homePopularTitle: "热门国家",
        homeFeaturedTitle: "推荐套餐",
        homeAiAssistantTitle: "智能旅行助手 🤖",
        homeAiAssistantDesc: "只需告诉我您要去哪里，我就会为您推荐最合适的套餐。",
        homeAiAssistantExample: "尝试：\"日本两周\"",
        homeAiFeature1: "💬 多语言支持",
        homeAiFeature2: "⚡ 即时响应",
        homeAiFeature3: "🎯 个性化建议",
        day: "天",
        viewPackages: "查看套餐",
        homeAiExample1: "日本 2周",
        homeAiExample2: "韩国 10 GB",
        plusCountries: "+ {count} 个国家",
        myEsimsHeroTitle: "我的 eSIM",
        myEsimsHeroDesc: "在此管理您购买的套餐",
        active: "激活",
        history: "历史",
        loginRequired: "需要登录",
        loginRequiredDesc: "请登录以查看您的订单。",
        noActiveEsims: "没有激活的 eSIM",
        noActiveEsimsDesc: "选择一个 eSIM 套餐并开始您的旅程。",
        noHistory: "历史记录为空",
        noHistoryDesc: "您的购买历史将显示在这里。",
        selectPackage: "选择套餐",
        statusActive: "激活",
        statusPending: "待处理",
        statusCompleted: "已完成",
        dataUsage: "数据使用量",
        daysRemaining: "剩余 {count} 天",
        select: "选择",
        cancel: "取消",
        selectAll: "全选",
        delete: "删除",
        esimDetails: "eSIM 详情",
        qrScanInstructions: "扫描下方二维码以激活您的 eSIM",
        downloadQr: "下载二维码 (图片)",
        download: "下载",
        qrOneTime: "代码只能扫描一次",
        manualEntry: "手动输入代码",
        iccid: "ICCID (序列号)",
        sendToFriend: "发送给朋友",
        installationGuide: "查看安装指南",
        featured: "推荐",
        regional: "地区",
        vpnIncluded: "包含 VPN",
        topUp: "充值",
        newEsim: "新 eSIM",
        topUpDesc: "仅限现有 eSIM 用户",
        topUpNoEsimError: "您没有可充值的有效 eSIM",
        topUpLoginRequired: "您必须登录才能购买充值。",
        topUpProviderError: "这只能为 {provider} eSIM 充值",
        incompatible: "不兼容",
        vpnFeatureTitle: "包含 VPN - 无限制访问",
        vpnFeatureDesc: "由于包含VPN，您可以无限制地自由访问 Facebook、Instagram、Youtube 和 Google 等被屏蔽的服务。",
        newPackagesBannerTitle: "获取新 eSIM",
        newPackagesBannerDesc: "以最实惠的价格在 200 多个国家/地区获取旅游数据。",
        topUpPackagesBannerTitle: "eSIM 充值",
        topUpPackagesBannerDesc: "使用无限高速数据为您活跃的 GateSIM eSIM 充值。",
        price: "价格",
        validity: "有效期",
        coverage: "覆盖范围",
        activation: "激活",
        instant: "立即",
        packageDetails: "套餐详情",
        compatibleDevices: "兼容设备",
        importantNotes: "重要提示",
        totalAmount: "应付总额",
        buyNow: "立即购买",
        checkoutTitle: "结账",
        receiveEmail: "联系邮箱",
        invalidEmail: "邮箱格式不正确",
        emailNote: "二维码将发送至此邮箱",
        paymentMethod: "付款方式",
        qpayDesc: "使用银行应用支付",
        internationalCard: "国际信用卡",
        comingSoon: "即将推出",
        payNow: "立即付款",
        paymentSuccess: "支付成功！",
        preparingEsim: "正在准备您的 eSIM...",
        orderConfirmed: "您的订单已确认。请查看您的邮箱。",
        orderNumber: "订单编号",
        backToHome: "返回首页",
        checkPayment: "检查支付状态",
        waitingPayment: "正在等待付款...",
        bankAppPay: "银行应用付款",
        summary: "摘要",
        package: "套餐",
        // Technical Info
        speed4G5G: "4G/5G 高速网络",
        noSpeedLimit: "不限速 (高速)",
        hotspotSupport: "支持热点分享",
        activationOnUse: "首次使用时开始计算有效期",
        emailDeliveryInfo: "eSIM 二维码将保存在“我的 eSIM”中（针对登录用户），并在 1-5 分钟内通过电子邮件发送。请确保您的设备支持 eSIM。",
        // Country Names
        country_JP: "日本",
        country_KR: "韩国",
        country_CN: "中国",
        country_TH: "泰国",
        country_SG: "新加坡",
        country_VN: "越南",
        country_TR: "土耳其",
        country_US: "美国",
        country_RU: "俄罗斯",
        country_KZ: "哈萨克斯坦",
        country_DE: "德国",
        country_FR: "法国",
        country_IT: "意大利",
        country_ES: "西班牙",
        country_NL: "荷兰",
        country_GB: "英国",
        country_EU: "欧洲",
        country_AL: "阿尔巴尼亚",
        country_AE: "阿联酋",
        country_HK: "香港",
        country_TW: "台湾",
        // Device Names
        devicePhone: "手机",
        yourPhone: "您的手机",
        compatibleIphone: "iPhone XR, XS, 11, 12, 13, 14, 15, 16 及更新机型。\n⚠️ 注意：中国大陆、香港、澳门版本的 iPhone（如 XS, 11, 12, 13...）通过不支持 eSIM（仅支持物理双卡）。",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold 系列。\n⚠️ 注意：中国大陆、香港、澳门版本通常不支持 eSIM。",
        compatiblePixel: "Google Pixel 3, 3XL, 4, 4XL, 5... 及所有更新机型。",
        // Expense Tracker
        aiScanReceipt: "扫描收据",
        aiScanDesc: "AI将分析您的收据并自动跟踪费用。",
        manualEntryTitle: "手动输入",
        newCategory: "新类别",
        categoryName: "类别名称",
        createCategory: "创建类别",
        merchantDetails: "商户详情",
        amountAndCurrency: "金额和货币",
        establishmentName: "场所名称",
        date: "日期",
        syncToHistory: "同步到历史记录",
        upload: "上传",
        camera: "相机",
        manual: "手动",
        // AI Hub Features
        aiHubTitle: "AI 枢纽",
        aiHubSubtitle: "智能中心",
        aiHubEngineReady: "AI 引擎就绪",
        aiHubStartJourney: "开始新旅程",
        aiHubUsageMonitoring: "使用情况监控",
        aiHubGoPro: "升级 Pro",
        aiHubPlans: "计划",
        aiHubAnalytics: "分析",
        aiHubAssets: "资产",
        aiFeaturePlannerTitle: "行程规划",
        aiFeaturePlannerDesc: "智能行程和路线规划",
        aiFeatureTransitTitle: "交通指南",
        aiFeatureTransitDesc: "使用 AI 进行无缝导航",
        aiFeatureTranslatorTitle: "翻译器",
        aiFeatureTranslatorDesc: "语音和文本翻译",
        aiFeaturePosterTitle: "记忆艺术",
        aiFeaturePosterDesc: "将照片转换为 AI 艺术",
        aiFeatureExpenseTitle: "支出追踪器",
        aiFeatureExpenseDesc: "智能旅行支出管理",
        aiFeatureMedicalTitle: "医疗助手",
        aiFeatureMedicalDesc: "寻找诊所并解释症状",
        aiStatusReading: "正在读取数据...",
        aiStaffNotFound: "未找到员工",
        aiStaffStart: "让我们开始吧！",
        confirmDelete: "您确定要删除吗？",
        confirmDeleteEsims: "从历史记录中删除 {count} 个套餐？",
        // Admin AI Staff
        adminAiStaffTitle: "AI 员工管理",
        adminAiStaffSubtitle: "数字办公室",
        adminLoadDefaults: "加载员工",
        adminAddNew: "添加新角色",
        adminSearchStaff: "搜索员工...",
        adminRoles: "角色",
        adminSales: "销售",
        adminTravel: "旅行",
        adminManager: "经理",
        adminActive: "有效",
        adminInactive: "下线",
        adminSetDefault: "设为默认",
        adminDefault: "默认",
        adminAllStaff: "所有员工",
        adminStaffPermissionDenied: "权限被拒绝。请检查 Firebase 规则。",
        adminHomeAdvisor: "家庭顾问",
        adminHubSpecialist: "中心专家",
        adminOfficeManager: "办公室经理",
        adminHomeSales: "销售辅助",
        adminHubGuide: "中心指南",
        adminExpert: "GateSIM 专家",
        // Inner AI Pages
        backToHub: "回到控制中心",
        // Budget
        budgetTitle: "预算",
        budgetSubtitle: "AI 支出控制",
        totalSpent: "总支出",
        recentExpenses: "最近历史",
        itemsCount: "{count} 个项目",
        noHistoryFound: "未找到历史记录",
        tapToScan: "点击扫描收据",
        expenseLabel: "支出",
        // Medical
        medicalTravelTitle: "医疗旅游",
        medicalTravelSubtitle: "韩国、泰国、土耳其、印度",
        medicalDestinationsTitle: "医疗旅游目的地",
        treatmentTypeTitle: "治疗类型",
        additionalInfoOptional: "附加信息（可选）",
        additionalInfoPlaceholder: "例如：韩国整容手术，特殊要求...",
        generateMedicalPlanBtn: "生成医疗旅行计划",
        medicalTripSummary: "医疗旅游",
        dayPlanCount: "{count} 天计划",
        hospitalInfoLabel: "医院信息",
        preTripChecklistLabel: "行前清单",
        activitiesCount: "{count} 项活动",
        recoveryLabel: "康复",
        // Transit
        transitGuideTitle: "交通指南",
        transitGuideSubtitle: "寻找最快、最便宜的路线",
        transitGreetingDefault: "您好，我是您的交通助手。您想去哪里？",
        transitGreetingItinerary: "我应该引导您去行程中的 \"{location}\" 吗？",
        transitGreetingDestination: "需要在 \"{destination}\" 游览时提供帮助吗？",
        nearestStationAction: "最近车站",
        nearestStationQuery: "最近的公交站/火车站 在哪里？",
        toHospitalAction: "去医院",
        toHospitalQuery: "我该如何去最近的医院？",
        subwayMapAction: "地铁图",
        subwayMapQuery: "给我看看地铁图",
        // Travel Memory
        memoryArtTitle: "记忆艺术",
        memoryArtSubtitle: "将照片转换为海报",
        uploadPhotoTitle: "上传照片",
        uploadPhotoDesc: "从设备中选择",
        takePhotoTitle: "拍摄照片",
        takePhotoDesc: "开启相机",
        aiEnhanceBtn: "AI 增强",
        filterLabel: "滤镜",
        addTextTitle: "添加文字",
        titlePlaceholder: "标题...",
        locationPlaceholder: "📍 地点",
        datePlaceholder: "📅 日期",
        textPosBottom: "底部",
        textPosTop: "顶部",
        textPosCenter: "中间",
        downloadBtn: "下载",
        shareBtn: "分享",
        // Translator
        translatorTitle: "翻译",
        translatorTextMode: "文本",
        translatorVoiceMode: "语音",
        translatorCameraMode: "相机",
        translatorInputLabel: "输入",
        translatorOutputLabel: "输出",
        translatorPlaceholder: "输入要翻译的文字...",
        translatorBtn: "翻译",
        translationFailed: "翻译失败",
        // Travel Planner
        plannerTitle: "行程规划",
        plannerSubtitle: "AI 打造完美行程",
        plannerStep1: "基础",
        plannerStep2: "目的",
        plannerStep3: "路线",
        plannerStep4: "发现",
        plannerStep5: "行程",
        plannerNext: "下一步",
        plannerBack: "上一步",
        plannerDuration: "多少天？",
        plannerBudget: "预算",
        plannerTravelers: "旅行者",
        plannerAdults: "成人",
        plannerChildren: "儿童",
        plannerTarget: "去哪里？",
        plannerStartDate: "出发日期",
        plannerPurposes: "旅行目的",
        plannerDiscovery: "发现",
        plannerGenerate: "生成行程",
        plannerGenerating: "规划中...",
        plannerAnalyzing: "分析旅行偏好...",
        plannerFinding: "寻找最佳航线和航班...",
        plannerCurating: "筛选高评分酒店和景点...",
        plannerFinalizing: "完成您的完美行程...",
        plannerSaveTrip: "保存行程",
        plannerSaved: "行程已保存",
        plannerSuggestCities: "建议城市",
        plannerAddCustomCity: "添加自定义城市",
        plannerSelectedHotels: "已选酒店",
        plannerItinerary: "旅行路线",
        plannerDailyPlan: "每日计划",
        plannerStep1Header: "1. 选择目的地和时长",
        plannerStep2Header: "2. 确定目的和交通方式",
        plannerDestinationLabel: "目的地",
        plannerSelectCountry: "选择国家",
        plannerDateLabel: "旅行日期",
        plannerPickDate: "选择日期",
        plannerDurationLabel: "行时长",
        plannerTotalDays: "总计天数",
        plannerChinaDistance: "离边境距离",
        plannerNear: "近",
        plannerNearDesc: "二连浩特、呼和浩特...",
        plannerMid: "中",
        plannerMidDesc: "北京、天津...",
        plannerFar: "远",
        plannerFarDesc: "上海、广州...",
        plannerSuggestNote: "* 将根据您的选择推荐城市",
        plannerTravelerAdult: "成人",
        plannerTravelerChild: "儿童",
        plannerTravelerNote: "* 预算将根据旅行者人数计算",
        plannerContinue: "继续",
        plannerPurposeLabel: "旅行目的",
        plannerTransportLabel: "交通方式选择",
        plannerTransportNote: "* 您的行程将根据这些选择进行定制",
        plannerTransportFlight: "飞机",
        plannerTransportTrain: "火车",
        plannerTransportBus: "巴士",
        plannerTransportMetro: "地铁",
        plannerTransportTaxi: "出租车",
        plannerInternational: "国际",
        plannerIntercity: "城市之间",
        plannerInnerCity: "城市内部",
        plannerSelectFlight: "选择航班",
        plannerSearchingFlights: "正在为您寻找最佳航班...",
        plannerFindFlights: "寻找航班",
        plannerFlightDirect: "直飞",
        plannerFlightStops: "{count} 站",
        plannerFlightRefresh: "刷新",
        plannerNeedsPlaceholder: "输入您的特殊需求...",
        plannerNeedsSuffix: "需求",
        plannerStep3Header: "3. 规划您的路线和城市",
        plannerStep4Header: "4. 选择酒店和住宿",
        plannerAISuggestedCities: "AI 推荐城市",
        plannerAddCity: "添加城市",
        plannerOtherCity: "其他城市...",
        plannerEnterCity: "输入城市",
        plannerCityNameQuery: "城市名称？",
        plannerTripSequence: "旅行顺序",
        plannerStart: "开始",
        plannerDest: "目的地",
        plannerBudgetLevel: "预算",
        plannerBudgetCheap: "经济型",
        plannerBudgetEconomy: "舒适型",
        plannerBudgetLuxury: "豪华型",
        plannerAdd: "添加",
        plannerChange: "更改",
        plannerSelect: "选择",
        plannerRemove: "删除",
        plannerYourFlight: "您的航班",
        plannerStep5Header: "5. 选择活动和体验",
        plannerAIRecommendationNote: "AI 100% 匹配您的旅行目标",
        plannerFilter: "筛选",
        plannerSort: "排序",
        plannerAllHotels: "所有酒店",
        plannerLiveData: "✅ 仅限实时数据",
        plannerStars4: "⭐️ 4星+",
        plannerRecommended: "推荐",
        plannerPriceLowToHigh: "价格：从低到高",
        plannerPriceHighToLow: "价格：从高到低",
        plannerRatingHigh: "评分：从高到低",
        plannerResultsFound: "个搜索结果",
        plannerMyChoice: "自己的选择",
        plannerMyChoiceDesc: "我将在这个城市安排自己的住宿。",
        plannerMyChoiceStayDesc: "无需从建议中选择。我将自己处理住宿。",
        plannerFlexible: "灵活",
        plannerViewDetails: "查看详情",
        plannerSkip: "跳过",
        plannerGeneratePlan: "生成计划",
        plannerWaitMoment: "请稍等...",
        plannerFreeTime: "我的选择 / 自由时间",
        plannerFreeTimeDesc: "没有特定活动，我将自己探索",
        plannerDecideLater: "我稍后决定我的活动",
        // Trip Purposes
        purposeTourist: "观光",
        purposeTouristDesc: "普通观光和热门景点",
        purposeRelaxation: "放松",
        purposeRelaxationDesc: "休闲、水疗和康体",
        purposeAdventure: "冒险",
        purposeAdventureDesc: "体育运动和刺激活动",
        purposeFamily: "家庭",
        purposeFamilyDesc: "适合儿童和成人的安全有趣场所",
        purposeRomantic: "浪漫",
        purposeRomanticDesc: "适合情侣和蜜月的特别场所",
        purposeCulture: "文化",
        purposeCultureDesc: "历史、博物馆和当地遗产",
        purposeShopping: "购物",
        purposeShoppingDesc: "商场、市场和精品店",
        purposeFoodie: "美食",
        purposeFoodieDesc: "高级餐饮和当地特色美食",
        purposeProcurement: "采购",
        purposeProcurementDesc: "批发市场、采购和工厂",
        purposeBusiness: "商务",
        purposeBusinessDesc: "工作相关和专业活动",
        purposeMedical: "医疗",
        purposeMedicalDesc: "检查、治疗和康复",
        purposeEducation: "教育",
        purposeEducationDesc: "学校、课程和游学",
        purposeEvent: "活动",
        purposeEventDesc: "节日、音乐会和展览",
        plannerLoginRequired: "请登录以保存行程",
        plannerSaveSuccess: "保存成功！您可以在个人资料中查看。",
        plannerSaveFail: "保存行程失败。",
        plannerPrintFail: "此设备不支持打印。请截图保存。",
        plannerShareTitle: "旅行计划",
        plannerShareText: "看看我的 {dest} 旅行计划吧！",
        plannerLinkCopied: "链接已复制到剪贴板！",
        plannerShareFail: "无法分享。请截图保存。",
        plannerDestinationAlert: "请选择目的地",
        plannerPurposeAlert: "请至少选择一个旅行目的",
        plannerCityAlert: "请至少选择一个城市",
        plannerItineraryReady: "完美行程已就绪",
        plannerDurLabel: "时长",
        plannerActivitiesCount: "项活动",
        plannerBudgetCalc: "预算计算",
        plannerSavePlan: "保存计划",
        plannerDownloadPDF: "下载 PDF",
        plannerAIInsight: "AI 见解",
        plannerGatheringInsights: "正在收集见解...",
        plannerAIProcessing: "AI 正在处理信息",
        plannerOverview: "概览",
        plannerHighlights: "亮点",
        plannerProTips: "专业建议",
        plannerCultureEttiquette: "文化与礼仪",
        plannerNoInsights: "未找到见解。",
        plannerClose: "关闭",
        plannerGotIt: "知道了",
        plannerTravelersLabel: "旅行者",
        wizardDestQuestion: "您计划去哪里？",
        wizardDestPlaceholder: "城市名称...",
        wizardDurQuestion: "您的旅行大概几天？",
        wizardDurPlaceholder: "天数...",
        wizardPurposeQuestion: "旅行的主要目的是什么？",
    },
};

const LanguageContext = createContext<{
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
} | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const { language, setLanguage } = useLanguageStore();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    const t = (key: string) => {
        const langData = translations[language] as Record<string, string>;
        const fallbackData = translations.mn as Record<string, string>;

        // Dynamic country name fallback
        if (key.startsWith("country_") && !langData[key] && !fallbackData[key]) {
            const countryCode = key.split("_")[1]?.toUpperCase();
            if (countryCode && countryCode.length === 2) {
                try {
                    // Use Intl.DisplayNames for automatic localization
                    const displayNames = new Intl.DisplayNames(
                        [language === "mn" ? "mn-MN" : language],
                        { type: "region" }
                    );
                    return displayNames.of(countryCode) || key;
                } catch (e) {
                    return key;
                }
            }
        }

        return langData[key] || fallbackData[key] || key;
    };

    if (!mounted) return null;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useTranslation() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useTranslation must be used within a LanguageProvider");
    }
    return context;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return { language: context.language, setLanguage: context.setLanguage };
}
