"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "mn" | "en" | "cn";

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
}

const useLanguageStore = create<LanguageState>()(
    persist(
        (set) => ({
            language: "mn",
            setLanguage: (lang) => set({ language: lang }),
        }),
        {
            name: "language-storage",
        }
    )
);

export const translations = {
    mn: {
        home: "Нүүр",
        packages: "Багцууд",
        myEsims: "Миний eSIM",
        profile: "Профайл",
        myProfile: "Миний мэдээлэл",
        user: "Хэрэглэгч",
        login: "Нэвтрэх",
        greeting: "Сайн байна уу",
        logout: "Гарах",
        save: "Хадгалах",
        saving: "Хадгалж байна...",
        appearance: "Харагдац",
        lightMode: "Өдөр",
        darkMode: "Шөнө",
        email: "И-мэйл хаяг",
        phone: "Утасны дугаар",
        phonePlaceholder: "Утасны дугаараа оруулна уу",
        back: "Буцах",
        loading: "Уншиж байна...",
        error: "Алдаа гарлаа",
        success: "Амжилттай",
        eSimPlatform: "eSIM Платформ",
        // Auth
        welcomeBack: "Эргэн тавтай морил",
        signUp: "Шинээр бүртгүүлэх",
        authSubtitle: "GateSIM-д нэгдэн дэлхийн хаана ч холбогдоорой",
        continueWithGoogle: "Google-ээр үргэлжлүүлэх",
        or: "эсвэл",
        password: "Нууц үг",
        noAccount: "Хаяг байхгүй юу?",
        alreadyRegistered: "Бүртгэлтэй юу?",
        phoneOptional: "Утасны дугаар (Заавал биш)",
        continueWithEmail: "И-мэйлээр үргэлжлүүлэх",
        magicLinkSubtitle: "Бид таны и-мэйл рүү нэвтрэх түр линк илгээх болно",
        emailPlaceholder: "Таны и-мэйл хаяг",
        magicLinkSent: "Нэвтрэх линк илгээгдлээ. И-мэйлээ шалгана уу.",
        forgotPassword: "Нууц үг мартсан уу?",
        forgotPasswordDesc: "Бүртгэлтэй и-мэйл хаягаа оруулж нууц үг сэргээх линк авна уу",
        sendResetLink: "Сэргээх линк илгээх",
        resetEmailSent: "И-мэйл илгээгдлээ",
        resetEmailSentDesc: "Нууц үг сэргээх линк и-мэйлээр илгээгдлээ. Шалгана уу.",
        backToLogin: "Нэвтрэх рүү буцах",
        // Filters
        duration1_7: "1-7 хоног",
        duration8_15: "8-15 хоног",
        duration15Plus: "15+ хоног",
        packagesFound: "Нийт {count} багц олдлоо",
        countryEsimPackages: "{country} eSIM Багцууд",
        all: "Бүгд",
        unlimited: "Хязгааргүй",
        noPackagesMatch: "Сонгосон шүүлтүүрт тохирох багц олдсонгүй.",
        clearFilters: "Шүүлтүүр арилгах",
        allCountries: "Бүх улс",
        searchPackagesPlaceholder: "Улс, багц хайх...",
        countPackages: "{count} багц",
        noPackagesFound: "Багц олдсонгүй",
        noPackagesDesc: "Хайлт эсвэл шүүлтүүрээ өөрчлөөд үзнэ үү.",
        loadingMore: "Ачааллаж байна...",
        scrollMore: "Доош гүйлгэж илүү ихийг үзнэ үү",
        allPackagesShown: "Бүх {count} багц харагдлаа ✓",
        // Nav
        navHome: "Нүүр",
        navPackages: "Багцууд",
        navMyEsim: "Миний eSIM",
        navProfile: "Профайл",
        // AI Chat
        aiTitle: "Аяллын туслах",
        aiDescription: "Ухаалаг зөвлөх",
        aiGuestMode: "Зочин горим",
        aiThinking: "Бодож байна...",
        aiPlaceholder: "Ямар багц хайж байна вэ?",
        aiPopularPackages: "Түгээмэл багцууд:",
        aiSeeAll: "Бүх багцыг үзэх",
        aiCompatibilityWarning: "Сайн байна уу! Таны {device} eSIM дэмжихгүй байж магадгүй байна. ⚠️\n\nТа худалдан авалт хийхээсээ өмнө төхөөрөмжөө eSIM дэмждэг эсэхийг шалгаарай.",
        aiGreeting1: "Сайн байна уу! Та аль улс руу, хэд хоногоор аялах гэж байна вэ? 🌍✈️",
        aiGreeting2: "Сайн байна уу! Танд аялах улсад чинь тохирох eSIM багц олоход туслах уу? 🗺️✨",
        aiGreeting3: "Сайн уу! Дараагийн аялал хаашаа вэ? Би танд хамгийн хямд багцыг олж өгч чадна. 🚀",
        aiGreeting4: "Сайн байна уу! Та аялах улсаа хэлээрэй, би хамгийн шилдэг багцуудыг санал болгоё. 💡",
        // Home
        homeHeroTitle: "Connectivity Everywhere",
        homeHeroSubtitle: "Your Global Gateway",
        homeHeroDesc: "Дэлхийн 200 гаруй улсад хамгийн хямд үнээр интернетэд холбогдоорой.",
        homeSearchPlaceholder: "Хаашаа аялах вэ?",
        homeDuration7: "7 хоног",
        homeDuration15: "15 хоног",
        homePopularTitle: "Түгээмэл улсууд",
        homeFeaturedTitle: "Онцлох багцууд",
        homeAiAssistantTitle: "Ухаалаг аяллын туслах 🤖",
        homeAiAssistantDesc: "Та хаашаа явахаа хэлэхэд л хангалттай, би танд хамгийн тохиромжтой багцыг санал болгоно.",
        homeAiAssistantExample: "Жишээ нь: \"Япон 2 долоо хоног\"",
        homeAiFeature1: "💬 Олон хэлээр ярьдаг",
        homeAiFeature2: "⚡ Шуурхай хариу",
        homeAiFeature3: "🎯 Хувийн зөвлөгөө",
        day: "хоног",
        viewPackages: "Багцуудыг үзэх",
        homeAiExample1: "Япон 2 долоо хоног",
        homeAiExample2: "Солонгос 10 ГБ",
        plusCountries: "+ {count} улс",
        myEsimsHeroTitle: "Миний eSIM",
        myEsimsHeroDesc: "Худалдаж авсан багцуудаа эндээс удирдаарай",
        active: "Идэвхтэй",
        history: "Түүх",
        loginRequired: "Нэвтрэх шаардлагатай",
        loginRequiredDesc: "Та өөрийн захиалгуудыг харахын тулд системд нэвтэрч орно уу.",
        noActiveEsims: "Идэвхтэй eSIM алга",
        noActiveEsimsDesc: "Дэлхийн хаана ч холбогдох боломжтой eSIM багцаа сонгоод аялалаа эхлүүлээрэй.",
        noHistory: "Түүх хоосон байна",
        noHistoryDesc: "Таны худалдан авалтын түүх энд харагдах болно.",
        selectPackage: "Багц сонгох",
        statusActive: "Идэвхтэй",
        statusPending: "Хүлээж байна",
        statusCompleted: "Дууссан",
        dataUsage: "Дата ашиглалт",
        daysRemaining: "{count} хоног үлдсэн",
        select: "Сонгох",
        cancel: "Болих",
        selectAll: "Бүгдийг сонгох",
        delete: "Устгах",
        esimDetails: "eSIM Дэлгэрэнгүй",
        qrScanInstructions: "Доорх QR кодыг уншуулж eSIM-ээ идэвхжүүлээрэй",
        downloadQr: "QR татах (Зураг)",
        download: "Татах",
        qrOneTime: "Код зөвхөн нэг удаа уншигдана",
        manualEntry: "Гараар оруулах код",
        iccid: "ICCID (Сериал дугаар)",
        sendToFriend: "Найздаа илгээх",
        installationGuide: "Суулгах заавар харах",
        featured: "Онцлох",
        regional: "Бүсийн",
        vpnIncluded: "VPN-тэй",
        topUp: "Цэнэглэлт",
        newEsim: "Шинэ eSIM",
        topUpDesc: "Зөвхөн өмнө нь исим авсан хэрэглэгчдэд",
        topUpNoEsimError: "Танд цэнэглэх идэвхтэй eSIM байхгүй байна",
        topUpLoginRequired: "Цэнэглэлт авахын тулд та нэвтэрсэн байх шаардлагатай.",
        topUpProviderError: "Зөвхөн {provider}-ийн eSIM-ийг цэнэглэх боломжтой",
        incompatible: "Тохирохгүй байна",
        vpnFeatureTitle: "VPN-тэй тул бүх сошиал руу чөлөөтэй орно",
        vpnFeatureDesc: "Facebook, Instagram, Youtube, Google зэрэг хориглогдсон бүх сүлжээ рүү ямар нэгэн хязгаарлалтгүйгээр чөлөөтэй нэвтрэнэ.",
        newPackagesBannerTitle: "Шинэ eSIM авах",
        newPackagesBannerDesc: "Та дэлхийн 200 гаруй улсад хамгийн хямд үнээр аялалын дата авах боломжтой.",
        topUpPackagesBannerTitle: "eSIM цэнэглэх",
        topUpPackagesBannerDesc: "Өмнө нь GateSIM-ээс авсан идэвхтэй eSIM-ээ ашиглан хурдны хязгааргүй датагаар цэнэглээрэй.",
        price: "Үнэ",
        validity: "Хугацаа",
        coverage: "Хамрах",
        activation: "Идэвхжих",
        instant: "Шууд",
        packageDetails: "Багцын дэлгэрэнгүй",
        compatibleDevices: "Нийцтэй төхөөрөмжүүд",
        importantNotes: "Анхаарах зүйлс",
        totalAmount: "Нийт төлөх",
        buyNow: "Авах",
        checkoutTitle: "Захиалга баталгаажуулах",
        receiveEmail: "Хүлээн авах имэйл",
        invalidEmail: "Буруу форматтай имэйл байна",
        emailNote: "QR код энэ хаягаар илгээгдэнэ",
        paymentMethod: "Төлбөрийн хэлбэр",
        qpayDesc: "Банкны аппаар төлөх",
        internationalCard: "Олон улсын карт",
        comingSoon: "Тун удахгүй",
        payNow: "Төлбөр төлөх",
        paymentSuccess: "Төлбөр амжилттай!",
        preparingEsim: "eSIM-ийг бэлтгэж байна...",
        orderConfirmed: "Таны захиалга баталгаажлаа. Имэйлээ шалгана уу.",
        orderNumber: "Захиалгын дугаар",
        backToHome: "Нүүр хуудас руу буцах",
        checkPayment: "Төлбөр шалгах",
        waitingPayment: "Төлбөр хүлээж байна...",
        bankAppPay: "Банкны аппаар төлөх",
        summary: "Товчоо",
        package: "Багц",
        // Technical Info
        speed4G5G: "4G/5G өндөр хурдны сүлжээ",
        noSpeedLimit: "Хурдны хязгааргүй (High Speed)",
        hotspotSupport: "Hotspot цацах боломжтой",
        activationOnUse: "Ашиглаж эхэлснээс хойш хугацаа тоологдоно",
        emailDeliveryInfo: "eSIM QR код 'Миний eSIM' цэсэнд хадгалагдах (нэвтэрсэн хэрэглэгч) болон таны и-мэйл хаягаар 1-5 минутын дотор ирнэ. Та зөвхөн eSIM дэмждэг утастай байх шаардлагатай.",
        // Country Names
        country_JP: "Япон",
        country_KR: "Солонгос",
        country_CN: "Хятад",
        country_TH: "Тайланд",
        country_SG: "Сингапур",
        country_VN: "Вьетнам",
        country_TR: "Турк",
        country_US: "Америк",
        country_RU: "Орос",
        country_KZ: "Казахстан",
        country_DE: "Герман",
        country_FR: "Франц",
        country_IT: "Итали",
        country_ES: "Испани",
        country_NL: "Нидерланд",
        country_GB: "Их Британи",
        country_EU: "Европ",
        country_AL: "Албани",
        country_AE: "Арабын Нэгдсэн Эмират",
        country_HK: "Хонг Конг",
        country_TW: "Тайвань",
        // Device Names
        devicePhone: "Утас",
        yourPhone: "Таны утас",
        compatibleIphone: "iPhone XR, XS, 11, 12, 13, 14, 15, 16 болон шинэ загварууд. \n⚠️ Анхааруулга: Хятад, Хонконг, Макаогаас авсан iPhone (XS, 11, 12, 13, 14, 15... гэх мэт) ихэнх загварууд eSIM дэмждэггүй (2 сим карт ордог тул).",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold цувралууд. \n⚠️ Анхааруулга: Хятад, Хонконг, Макао хувилбарууд ихэвчлэн eSIM дэмждэггүй.",
        compatiblePixel: "Google Pixel 3, 3XL, 4, 4XL, 5... болон түүнээс хойшхи бүх загварууд.",
        // Expense Tracker
        aiScanReceipt: "Баримт уншуулах",
        aiScanDesc: "AI таны баримтыг уншиж, зардлыг автоматаар бүртгэнэ.",
        manualEntryTitle: "Гараар бүртгэх",
        newCategory: "Шинэ ангилал",
        categoryName: "Ангиллын нэр",
        createCategory: "Ангилал үүсгэх",
        merchantDetails: "Гүйлгээний мэдээлэл",
        amountAndCurrency: "Дүн & Валют",
        establishmentName: "Байгууллагын нэр",
        date: "Огноо",
        syncToHistory: "Түүх рүү хадгалах",
        upload: "Зураг оруулах",
        camera: "Камер",
        manual: "Гараар",
        // AI Hub Features
        aiHubTitle: "AI Hub",
        aiHubSubtitle: "Ухаалаг төв",
        aiHubEngineReady: "AI Engine бэлэн",
        aiHubStartJourney: "Шинэ аялал эхлүүлэх",
        aiHubUsageMonitoring: "Ашиглалтын хяналт",
        aiHubGoPro: "Pro болох",
        aiHubPlans: "Төлөвлөгөө",
        aiHubAnalytics: "Аналитик",
        aiHubAssets: "Ассет",
        aiFeaturePlannerTitle: "Аялал Төлөвлөгч",
        aiFeaturePlannerDesc: "Маршрут болон төлөвлөгөө боловсруулах",
        aiFeatureTransitTitle: "Нийтийн Тээвэр",
        aiFeatureTransitDesc: "Цэвэрхэн, хялбар замын хөтөч",
        aiFeatureTranslatorTitle: "Орчуулагч",
        aiFeatureTranslatorDesc: "Дуут болон бичгэн орчуулга",
        aiFeaturePosterTitle: "Аялалын Дурсамж",
        aiFeaturePosterDesc: "Зургийг арт болгож хувиргах",
        aiFeatureExpenseTitle: "Зардал Хөтлөгч",
        aiFeatureExpenseDesc: "Аялалын зардлаа хялбар удирдах",
        aiFeatureMedicalTitle: "Эмчилгээний Туслах",
        aiFeatureMedicalDesc: "Эмнэлэг хайх, шинж тэмдэг тайлбарлах",
        aiStatusReading: "Мэдээлэл уншиж байна...",
        aiStaffNotFound: "Ажилтан олдсонгүй",
        aiStaffStart: "Захирал аа, эхлүүлцгээе!",
        confirmDelete: "Та устгахдаа итгэлтэй байна уу?",
        confirmDeleteEsims: "{count} багцыг түүхээс устгах уу?",
        // Admin AI Staff
        adminAiStaffTitle: "AI Ажилчдын удирдлага",
        adminAiStaffSubtitle: "ДИЖИТАЛ ОФФИС",
        adminLoadDefaults: "Ажилчдыг ачаалах",
        adminAddNew: "Шинэ дүр нэмэх",
        adminSearchStaff: "Ажилтан хайх...",
        adminRoles: "Үүргүүд",
        adminSales: "Борлуулалт",
        adminTravel: "Аялал",
        adminManager: "Менежер",
        adminActive: "Идэвхтэй",
        adminInactive: "Идэвхгүй",
        adminSetDefault: "Үндсэн болгох",
        adminDefault: "Үндсэн",
        adminAllStaff: "Бүх ажилчид",
        adminStaffPermissionDenied: "Хандах эрх хүрэлцэхгүй байна. Firebase Rules-ээ шинэчилнэ үү.",
        adminHomeAdvisor: "Зөвлөх (Нүүр)",
        adminHubSpecialist: "Мэргэжилтэн (Hub)",
        adminOfficeManager: "Оффис Менежер",
        adminHomeSales: "HOME SALES",
        adminHubGuide: "HUB GUIDE",
        adminExpert: "GateSIM Экперт",
    },
    en: {
        home: "Home",
        packages: "Packages",
        myEsims: "My eSIM",
        profile: "Profile",
        myProfile: "My Profile",
        user: "User",
        login: "Login",
        greeting: "Hello",
        logout: "Logout",
        save: "Save",
        saving: "Saving...",
        appearance: "Appearance",
        lightMode: "Light",
        darkMode: "Dark",
        email: "Email Address",
        phone: "Phone Number",
        phonePlaceholder: "Enter your phone number",
        back: "Back",
        loading: "Loading...",
        error: "An error occurred",
        success: "Success",
        eSimPlatform: "eSIM Platform",
        // Auth
        welcomeBack: "Welcome Back",
        signUp: "Sign Up",
        authSubtitle: "Join GateSIM and connect anywhere in the world",
        continueWithGoogle: "Continue with Google",
        or: "or",
        password: "Password",
        noAccount: "Don't have an account?",
        alreadyRegistered: "Already registered?",
        phoneOptional: "Phone Number (Optional)",
        continueWithEmail: "Continue with Email",
        magicLinkSubtitle: "We will send you a temporary login link to your email",
        emailPlaceholder: "Your email address",
        magicLinkSent: "Login link sent. Please check your email.",
        forgotPassword: "Forgot Password?",
        forgotPasswordDesc: "Enter your registered email to receive a reset link",
        sendResetLink: "Send Reset Link",
        resetEmailSent: "Email Sent",
        resetEmailSentDesc: "A password reset link has been sent to your email.",
        backToLogin: "Back to Login",
        // Filters
        duration1_7: "1-7 Days",
        duration8_15: "8-15 Days",
        duration15Plus: "15+ Days",
        packagesFound: "Total {count} packages found",
        countryEsimPackages: "{country} eSIM Packages",
        all: "All",
        unlimited: "Unlimited",
        noPackagesMatch: "No packages match the selected filters.",
        clearFilters: "Clear Filters",
        allCountries: "All Countries",
        searchPackagesPlaceholder: "Search countries, packages...",
        countPackages: "{count} packages",
        noPackagesFound: "No packages found",
        noPackagesDesc: "Try changing your search or filters.",
        loadingMore: "Loading...",
        scrollMore: "Scroll down for more",
        allPackagesShown: "All {count} packages shown ✓",
        // Nav
        navHome: "Home",
        navPackages: "Packages",
        navMyEsim: "My eSIM",
        navProfile: "Profile",
        // AI Chat
        aiTitle: "AI Assistant",
        aiDescription: "Smart Advisor",
        aiGuestMode: "Guest Mode (eSIM only)",
        aiThinking: "Thinking...",
        aiPlaceholder: "What package are you looking for?",
        aiPopularPackages: "Popular Searches:",
        aiSeeAll: "See all packages",
        aiCompatibilityWarning: "Hello! Your {device} might not support eSIM. ⚠️\n\nPlease check compatibility before purchasing.",
        aiGreeting1: "Hello! Where are you traveling to, and for how long? 🌍✈️",
        aiGreeting2: "Hello! Can I help you find a suitable eSIM package for your trip? 🗺️✨",
        aiGreeting3: "Hi! Where's your next trip? I can find the best package for you. 🚀",
        aiGreeting4: "Hello! Tell me which country you're traveling to, and I'll show you the best packages. 💡",
        // Home
        homeHeroTitle: "Connectivity Everywhere",
        homeHeroSubtitle: "Your Global Gateway",
        homeHeroDesc: "Connect to the internet in 200+ countries at the most affordable prices.",
        homeSearchPlaceholder: "Where are you going?",
        homeDuration7: "7 Days",
        homeDuration15: "15 Days",
        homePopularTitle: "Popular Countries",
        homeFeaturedTitle: "Featured Packages",
        homeAiAssistantTitle: "Smart Travel Assistant 🤖",
        homeAiAssistantDesc: "Just tell me where you're going, and I'll recommend the best package for you.",
        homeAiAssistantExample: "Try: \"Japan for 2 weeks\"",
        homeAiFeature1: "💬 Multilingual",
        homeAiFeature2: "⚡ Instant Response",
        homeAiFeature3: "🎯 Personalized Advice",
        day: "days",
        viewPackages: "View Packages",
        homeAiExample1: "Japan 2 weeks",
        homeAiExample2: "Korea 10 GB",
        plusCountries: "+ {count} countries",
        myEsimsHeroTitle: "My eSIMs",
        myEsimsHeroDesc: "Manage your purchased packages here",
        active: "Active",
        history: "History",
        loginRequired: "Login Required",
        loginRequiredDesc: "Please login to view your orders.",
        noActiveEsims: "No active eSIMs",
        noActiveEsimsDesc: "Choose an eSIM package and start your journey.",
        noHistory: "History is empty",
        noHistoryDesc: "Your purchase history will appear here.",
        selectPackage: "Select Package",
        statusActive: "Active",
        statusPending: "Pending",
        statusCompleted: "Completed",
        dataUsage: "Data Usage",
        daysRemaining: "{count} days remaining",
        select: "Select",
        cancel: "Cancel",
        selectAll: "Select All",
        delete: "Delete",
        esimDetails: "eSIM Details",
        qrScanInstructions: "Scan the QR code below to activate your eSIM",
        downloadQr: "Download QR (Image)",
        download: "Download",
        qrOneTime: "Code can only be scanned once",
        manualEntry: "Manual Entry Code",
        iccid: "ICCID (Serial Number)",
        sendToFriend: "Send to Friend",
        installationGuide: "View Installation Guide",
        featured: "Featured",
        regional: "Regional",
        vpnIncluded: "VPN Included",
        topUp: "Top-up",
        newEsim: "New eSIM",
        topUpDesc: "For existing eSIM users only",
        topUpNoEsimError: "You don't have an active eSIM to top up",
        topUpLoginRequired: "You must be logged in to purchase a top-up.",
        topUpProviderError: "This can only top up {provider} eSIMs",
        incompatible: "Incompatible",
        vpnFeatureTitle: "VPN Included - Unrestricted Access",
        vpnFeatureDesc: "Freely access blocked services like Facebook, Instagram, Youtube, and Google without any restrictions.",
        newPackagesBannerTitle: "Get New eSIM",
        newPackagesBannerDesc: "Get travel data in over 200 countries at the most affordable prices.",
        topUpPackagesBannerTitle: "Top-up eSIM",
        topUpPackagesBannerDesc: "Top up your active GateSIM eSIM with unlimited high-speed data.",
        price: "Price",
        validity: "Validity",
        coverage: "Coverage",
        activation: "Activation",
        instant: "Instant",
        packageDetails: "Package Details",
        compatibleDevices: "Compatible Devices",
        importantNotes: "Important Notes",
        totalAmount: "Total Amount",
        buyNow: "Buy Now",
        checkoutTitle: "Checkout",
        receiveEmail: "Contact Email",
        invalidEmail: "Invalid email format",
        emailNote: "QR code will be sent to this email",
        paymentMethod: "Payment Method",
        qpayDesc: "Pay with Banking App",
        internationalCard: "International Card",
        comingSoon: "Coming Soon",
        payNow: "Pay Now",
        paymentSuccess: "Payment Success!",
        preparingEsim: "Preparing your eSIM...",
        orderConfirmed: "Your order is confirmed. Please check your email.",
        orderNumber: "Order Number",
        backToHome: "Back to Home",
        checkPayment: "Check Payment",
        waitingPayment: "Waiting for payment...",
        bankAppPay: "Pay with Bank App",
        summary: "Summary",
        package: "Package",
        // Technical Info
        speed4G5G: "4G/5G High Speed Network",
        noSpeedLimit: "No Speed Limit (High Speed)",
        hotspotSupport: "Hotspot/Tethering Supported",
        activationOnUse: "Validity starts upon first connection",
        emailDeliveryInfo: "eSIM QR code will be saved in 'My eSIMs' (for logged-in users) and sent to your email within 1-5 minutes. Ensure your device is eSIM compatible.",
        // Country Names
        country_JP: "Japan",
        country_KR: "South Korea",
        country_CN: "China",
        country_TH: "Thailand",
        country_SG: "Singapore",
        country_VN: "Vietnam",
        country_TR: "Turkey",
        country_US: "USA",
        country_RU: "Russia",
        country_KZ: "Kazakhstan",
        country_DE: "Germany",
        country_FR: "France",
        country_IT: "Italy",
        country_ES: "Spain",
        country_NL: "Netherlands",
        country_GB: "United Kingdom",
        country_EU: "Europe",
        country_AL: "Albania",
        country_AE: "United Arab Emirates",
        country_HK: "Hong Kong",
        country_TW: "Taiwan",
        // Device Names
        devicePhone: "Phone",
        yourPhone: "Your Phone",
        compatibleIphone: "iPhone XR, XS, 11, 12, 13, 14, 15, 16 and newer models. \n⚠️ Warning: Most iPhones purchased in China, Hong Kong, or Macau (e.g. XS, 11, 12, 13...) do NOT support eSIM (Physical Dual SIM only).",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold series. \n⚠️ Warning: Models from China, Hong Kong, and Macau typically do NOT support eSIM.",
        compatiblePixel: "Google Pixel 3, 3XL, 4, 4XL, 5... and all newer models.",
        // Expense Tracker
        aiScanReceipt: "Scan Receipt",
        aiScanDesc: "AI will analyze your receipt and track expenses automatically.",
        manualEntryTitle: "Manual Entry",
        newCategory: "New Category",
        categoryName: "Category Name",
        createCategory: "Create Category",
        merchantDetails: "Merchant Details",
        amountAndCurrency: "Amount & Currency",
        establishmentName: "Establishment Name",
        date: "Date",
        syncToHistory: "Sync to History",
        upload: "Upload",
        camera: "Camera",
        manual: "Manual",
        // AI Hub Features
        aiHubTitle: "AI Hub",
        aiHubSubtitle: "Intelligence Center",
        aiHubEngineReady: "AI Engine Ready",
        aiHubStartJourney: "Start New Journey",
        aiHubUsageMonitoring: "Usage Monitoring",
        aiHubGoPro: "Go Pro",
        aiHubPlans: "Plans",
        aiHubAnalytics: "Analytics",
        aiHubAssets: "Assets",
        aiFeaturePlannerTitle: "Trip Planner",
        aiFeaturePlannerDesc: "Smart itinerary and route planning",
        aiFeatureTransitTitle: "Transit Guide",
        aiFeatureTransitDesc: "Seamless navigation with AI",
        aiFeatureTranslatorTitle: "Translator",
        aiFeatureTranslatorDesc: "Voice and text translation",
        aiFeaturePosterTitle: "Memory Art",
        aiFeaturePosterDesc: "Turn photos into AI art",
        aiFeatureExpenseTitle: "Expense Tracker",
        aiFeatureExpenseDesc: "Smart travel expense management",
        aiFeatureMedicalTitle: "Medical Assistant",
        aiFeatureMedicalDesc: "Find clinics and explain symptoms",
        aiStatusReading: "Reading data...",
        aiStaffNotFound: "No staff found",
        aiStaffStart: "Let's get started!",
        confirmDelete: "Are you sure you want to delete?",
        confirmDeleteEsims: "Delete {count} packages from history?",
        // Admin AI Staff
        adminAiStaffTitle: "AI Staff Management",
        adminAiStaffSubtitle: "DIGITAL OFFICE",
        adminLoadDefaults: "Load Staff",
        adminAddNew: "Add New Role",
        adminSearchStaff: "Search Staff...",
        adminRoles: "Roles",
        adminSales: "Sales",
        adminTravel: "Travel",
        adminManager: "Manager",
        adminActive: "Active",
        adminInactive: "Inactive",
        adminSetDefault: "Set as Default",
        adminDefault: "Default",
        adminAllStaff: "All Staff",
        adminStaffPermissionDenied: "Permission denied. Please check Firebase Rules.",
        adminHomeAdvisor: "Home Advisor",
        adminHubSpecialist: "Hub Specialist",
        adminOfficeManager: "Office Manager",
        adminHomeSales: "HOME SALES",
        adminHubGuide: "HUB GUIDE",
        adminExpert: "GateSIM Expert",
    },
    cn: {
        home: "首页",
        packages: "套餐",
        myEsims: "我的eSIM",
        profile: "个人资料",
        myProfile: "我的资料",
        user: "用户",
        login: "登录",
        greeting: "你好",
        logout: "注销",
        save: "保存",
        saving: "正在保存...",
        appearance: "外观",
        lightMode: "日间",
        darkMode: "夜间",
        email: "电子邮箱",
        phone: "电话号码",
        phonePlaceholder: "输入您的电话号码",
        back: "返回",
        loading: "加载中...",
        error: "发生错误",
        success: "成功",
        eSimPlatform: "eSIM 平台",
        // Auth
        welcomeBack: "欢迎回来",
        signUp: "注册",
        authSubtitle: "加入 GateSIM，随时随地保持联系",
        continueWithGoogle: "使用 Google 继续",
        or: "或",
        password: "密码",
        noAccount: "还没有账户？",
        alreadyRegistered: "已经注册了？",
        phoneOptional: "电话号码 (可选)",
        continueWithEmail: "使用电子邮件继续",
        magicLinkSubtitle: "我们将向您的邮箱发送一个临时登录链接",
        emailPlaceholder: "您的电子邮箱地址",
        magicLinkSent: "登录链接已发送。请检查您的邮箱。",
        forgotPassword: "忘记密码？",
        forgotPasswordDesc: "输入您注册的邮箱以接收重置链接",
        sendResetLink: "发送重置链接",
        resetEmailSent: "邮件已发送",
        resetEmailSentDesc: "密码重置链接已发送到您的邮箱。",
        backToLogin: "返回登录",
        // Filters
        duration1_7: "1-7天",
        duration8_15: "8-15天",
        duration15Plus: "15+天",
        packagesFound: "共找到 {count} 个套餐",
        countryEsimPackages: "{country} eSIM 套餐",
        all: "全部",
        unlimited: "无限",
        noPackagesMatch: "没有符合所选过滤条件的套餐。",
        clearFilters: "清除筛选",
        allCountries: "所有国家",
        searchPackagesPlaceholder: "搜索国家或套餐...",
        countPackages: "{count} 个套餐",
        noPackagesFound: "未找到套餐",
        noPackagesDesc: "请尝试更改搜索或过滤器。",
        loadingMore: "加载中...",
        scrollMore: "向下滑动查看更多",
        allPackagesShown: "已显示全部 {count} 个套餐 ✓",
        // Nav
        navHome: "首页",
        navPackages: "套餐",
        navMyEsim: "我的eSIM",
        navProfile: "个人资料",
        // AI Chat
        aiTitle: "AI 助手",
        aiDescription: "智能建议",
        aiGuestMode: "游客模式 (仅限 eSIM)",
        aiThinking: "思考中...",
        aiPlaceholder: "您在寻找什么套餐？",
        aiPopularPackages: "热门套餐：",
        aiSeeAll: "查看所有套餐",
        aiCompatibilityWarning: "您好！您的 {device} 可能不支持 eSIM。⚠️\n\n请在购买前检查设备兼容性。",
        aiGreeting1: "您好！您要去哪里旅行，打算呆多久？🌍✈️",
        aiGreeting2: "您好！我可以帮您找到适合旅行的 eSIM 套餐吗？🗺️✨",
        aiGreeting3: "嗨！您的下一次旅行去哪里？我可以为您找到最合适的套餐。🚀",
        aiGreeting4: "您好！告诉我您要去哪个国家，我会为您推荐最合适的套餐。💡",
        // Home
        homeHeroTitle: "全球互联",
        homeHeroSubtitle: "您的全球门户",
        homeHeroDesc: "以最实惠的价格在 200 多个国家/地区连接互联网。",
        homeSearchPlaceholder: "您要去哪里？",
        homeDuration7: "7天",
        homeDuration15: "15天",
        homePopularTitle: "热门国家",
        homeFeaturedTitle: "推荐套餐",
        homeAiAssistantTitle: "智能旅行助手 🤖",
        homeAiAssistantDesc: "只需告诉我您要去哪里，我就会为您推荐最合适的套餐。",
        homeAiAssistantExample: "尝试：\"日本两周\"",
        homeAiFeature1: "💬 多语言支持",
        homeAiFeature2: "⚡ 即时响应",
        homeAiFeature3: "🎯 个性化建议",
        day: "天",
        viewPackages: "查看套餐",
        homeAiExample1: "日本 2周",
        homeAiExample2: "韩国 10 GB",
        plusCountries: "+ {count} 个国家",
        myEsimsHeroTitle: "我的 eSIM",
        myEsimsHeroDesc: "在此管理您购买的套餐",
        active: "激活",
        history: "历史",
        loginRequired: "需要登录",
        loginRequiredDesc: "请登录以查看您的订单。",
        noActiveEsims: "没有激活的 eSIM",
        noActiveEsimsDesc: "选择一个 eSIM 套餐并开始您的旅程。",
        noHistory: "历史记录为空",
        noHistoryDesc: "您的购买历史将显示在这里。",
        selectPackage: "选择套餐",
        statusActive: "激活",
        statusPending: "待处理",
        statusCompleted: "已完成",
        dataUsage: "数据使用量",
        daysRemaining: "剩余 {count} 天",
        select: "选择",
        cancel: "取消",
        selectAll: "全选",
        delete: "删除",
        esimDetails: "eSIM 详情",
        qrScanInstructions: "扫描下方二维码以激活您的 eSIM",
        downloadQr: "下载二维码 (图片)",
        download: "下载",
        qrOneTime: "代码只能扫描一次",
        manualEntry: "手动输入代码",
        iccid: "ICCID (序列号)",
        sendToFriend: "发送给朋友",
        installationGuide: "查看安装指南",
        featured: "推荐",
        regional: "地区",
        vpnIncluded: "包含 VPN",
        topUp: "充值",
        newEsim: "新 eSIM",
        topUpDesc: "仅限现有 eSIM 用户",
        topUpNoEsimError: "您没有可充值的有效 eSIM",
        topUpLoginRequired: "您必须登录才能购买充值。",
        topUpProviderError: "这只能为 {provider} eSIM 充值",
        incompatible: "不兼容",
        vpnFeatureTitle: "包含 VPN - 无限制访问",
        vpnFeatureDesc: "由于包含VPN，您可以无限制地自由访问 Facebook、Instagram、Youtube 和 Google 等被屏蔽的服务。",
        newPackagesBannerTitle: "获取新 eSIM",
        newPackagesBannerDesc: "以最实惠的价格在 200 多个国家/地区获取旅游数据。",
        topUpPackagesBannerTitle: "eSIM 充值",
        topUpPackagesBannerDesc: "使用无限高速数据为您活跃的 GateSIM eSIM 充值。",
        price: "价格",
        validity: "有效期",
        coverage: "覆盖范围",
        activation: "激活",
        instant: "立即",
        packageDetails: "套餐详情",
        compatibleDevices: "兼容设备",
        importantNotes: "重要提示",
        totalAmount: "应付总额",
        buyNow: "立即购买",
        checkoutTitle: "结账",
        receiveEmail: "联系邮箱",
        invalidEmail: "邮箱格式不正确",
        emailNote: "二维码将发送至此邮箱",
        paymentMethod: "付款方式",
        qpayDesc: "使用银行应用支付",
        internationalCard: "国际信用卡",
        comingSoon: "即将推出",
        payNow: "立即付款",
        paymentSuccess: "支付成功！",
        preparingEsim: "正在准备您的 eSIM...",
        orderConfirmed: "您的订单已确认。请查看您的邮箱。",
        orderNumber: "订单编号",
        backToHome: "返回首页",
        checkPayment: "检查支付状态",
        waitingPayment: "正在等待付款...",
        bankAppPay: "银行应用付款",
        summary: "摘要",
        package: "套餐",
        // Technical Info
        speed4G5G: "4G/5G 高速网络",
        noSpeedLimit: "不限速 (高速)",
        hotspotSupport: "支持热点分享",
        activationOnUse: "首次使用时开始计算有效期",
        emailDeliveryInfo: "eSIM 二维码将保存在“我的 eSIM”中（针对登录用户），并在 1-5 分钟内通过电子邮件发送。请确保您的设备支持 eSIM。",
        // Country Names
        country_JP: "日本",
        country_KR: "韩国",
        country_CN: "中国",
        country_TH: "泰国",
        country_SG: "新加坡",
        country_VN: "越南",
        country_TR: "土耳其",
        country_US: "美国",
        country_RU: "俄罗斯",
        country_KZ: "哈萨克斯坦",
        country_DE: "德国",
        country_FR: "法国",
        country_IT: "意大利",
        country_ES: "西班牙",
        country_NL: "荷兰",
        country_GB: "英国",
        country_EU: "欧洲",
        country_AL: "阿尔巴尼亚",
        country_AE: "阿联酋",
        country_HK: "香港",
        country_TW: "台湾",
        // Device Names
        devicePhone: "手机",
        yourPhone: "您的手机",
        compatibleIphone: "iPhone XR, XS, 11, 12, 13, 14, 15, 16 及更新机型。\n⚠️ 注意：中国大陆、香港、澳门版本的 iPhone（如 XS, 11, 12, 13...）通过不支持 eSIM（仅支持物理双卡）。",
        compatibleSamsung: "Samsung Galaxy S20, S21, S22, S23, S24, Z Flip, Z Fold 系列。\n⚠️ 注意：中国大陆、香港、澳门版本通常不支持 eSIM。",
        compatiblePixel: "Google Pixel 3, 3XL, 4, 4XL, 5... 及所有更新机型。",
        // Expense Tracker
        aiScanReceipt: "扫描收据",
        aiScanDesc: "AI将分析您的收据并自动跟踪费用。",
        manualEntryTitle: "手动输入",
        newCategory: "新类别",
        categoryName: "类别名称",
        createCategory: "创建类别",
        merchantDetails: "商户详情",
        amountAndCurrency: "金额和货币",
        establishmentName: "场所名称",
        date: "日期",
        syncToHistory: "同步到历史记录",
        upload: "上传",
        camera: "相机",
        manual: "手动",
        // AI Hub Features
        aiHubTitle: "AI 枢纽",
        aiHubSubtitle: "智能中心",
        aiHubEngineReady: "AI 引擎就绪",
        aiHubStartJourney: "开始新旅程",
        aiHubUsageMonitoring: "使用情况监控",
        aiHubGoPro: "升级 Pro",
        aiHubPlans: "计划",
        aiHubAnalytics: "分析",
        aiHubAssets: "资产",
        aiFeaturePlannerTitle: "行程规划",
        aiFeaturePlannerDesc: "智能行程和路线规划",
        aiFeatureTransitTitle: "交通指南",
        aiFeatureTransitDesc: "使用 AI 进行无缝导航",
        aiFeatureTranslatorTitle: "翻译器",
        aiFeatureTranslatorDesc: "语音和文本翻译",
        aiFeaturePosterTitle: "记忆艺术",
        aiFeaturePosterDesc: "将照片转换为 AI 艺术",
        aiFeatureExpenseTitle: "支出追踪器",
        aiFeatureExpenseDesc: "智能旅行支出管理",
        aiFeatureMedicalTitle: "医疗助手",
        aiFeatureMedicalDesc: "寻找诊所并解释症状",
        aiStatusReading: "正在读取数据...",
        aiStaffNotFound: "未找到员工",
        aiStaffStart: "让我们开始吧！",
        confirmDelete: "您确定要删除吗？",
        confirmDeleteEsims: "从历史记录中删除 {count} 个套餐？",
        // Admin AI Staff
        adminAiStaffTitle: "AI 员工管理",
        adminAiStaffSubtitle: "数字办公室",
        adminLoadDefaults: "加载员工",
        adminAddNew: "添加新角色",
        adminSearchStaff: "搜索员工...",
        adminRoles: "角色",
        adminSales: "销售",
        adminTravel: "旅行",
        adminManager: "经理",
        adminActive: "有效",
        adminInactive: "下线",
        adminSetDefault: "设为默认",
        adminDefault: "默认",
        adminAllStaff: "所有员工",
        adminStaffPermissionDenied: "权限被拒绝。请检查 Firebase 规则。",
        adminHomeAdvisor: "家庭顾问",
        adminHubSpecialist: "中心专家",
        adminOfficeManager: "办公室经理",
        adminHomeSales: "销售辅助",
        adminHubGuide: "中心指南",
        adminExpert: "GateSIM 专家",
    },
};

const LanguageContext = createContext<{
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
} | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const { language, setLanguage } = useLanguageStore();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    const t = (key: string) => {
        const langData = translations[language] as Record<string, string>;
        const fallbackData = translations.mn as Record<string, string>;

        // Dynamic country name fallback
        if (key.startsWith("country_") && !langData[key] && !fallbackData[key]) {
            const countryCode = key.split("_")[1]?.toUpperCase();
            if (countryCode && countryCode.length === 2) {
                try {
                    // Use Intl.DisplayNames for automatic localization
                    const displayNames = new Intl.DisplayNames(
                        [language === "mn" ? "mn-MN" : language],
                        { type: "region" }
                    );
                    return displayNames.of(countryCode) || key;
                } catch (e) {
                    return key;
                }
            }
        }

        return langData[key] || fallbackData[key] || key;
    };

    if (!mounted) return null;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useTranslation() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useTranslation must be used within a LanguageProvider");
    }
    return context;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return { language: context.language, setLanguage: context.setLanguage };
}
