export interface UserData {
    uid: string;
    email: string;
    displayName?: string;
    photoURL?: string;
    phone?: string;
    role: 'user' | 'admin';
    createdAt: number; // Timestamp
    updatedAt: number;
}

export interface OrderItem {
    id?: string;
    sku: string;
    name: string;
    price: number; // Unit price in MNT
    currency?: string;
    quantity: number;
    countryCode?: string; // For analytics
    metadata?: any;
}

export interface Order {
    id: string; // Generated by Firestore or Custom ID
    userId: string;
    items: OrderItem[];
    totalAmount: number;
    currency: string;
    status: 'pending' | 'paid' | 'processing' | 'completed' | 'failed' | 'refunded';
    paymentMethod: 'qpay' | 'card' | 'socialpay' | 'stripe';
    paymentId?: string; // External Payment ID (e.g., QPay Invoice ID)
    contactEmail: string;
    contactPhone?: string;
    createdAt: number;
    updatedAt: number;

    // MobiMatter Specifics
    mobimatterOrderId?: string;
    esimIccid?: string;
    esimSmdpAddress?: string;
    esimActivationCode?: string;
}

export interface ProductCache {
    sku: string;
    data: any; // Full JSON from MobiMatter
    updatedAt: number;
}
