export interface UserData {
    uid: string;
    email: string;
    displayName?: string;
    photoURL?: string;
    phone?: string;
    role: 'user' | 'admin';
    createdAt: number; // Timestamp
    updatedAt: number;
}

export interface OrderItem {
    id?: string;
    sku: string;
    name: string;
    price: number; // Unit price in MNT
    currency?: string;
    quantity: number;
    countryCode?: string; // For analytics
    metadata?: Record<string, unknown>;
}

export interface Order {
    id: string; // Generated by Firestore or Custom ID
    userId: string;
    items: OrderItem[];
    totalAmount: number;
    currency: string;
    status: 'pending' | 'paid' | 'processing' | 'PROVISIONING' | 'PROVISIONING_FAILED' | 'COMPLETED' | 'completed' | 'failed' | 'refunded';
    paymentMethod: 'qpay' | 'card' | 'socialpay' | 'stripe';
    paymentId?: string; // External Payment ID (e.g., QPay Invoice ID)
    contactEmail: string;
    contactPhone?: string;
    createdAt: number;
    updatedAt: number;

    // Extended Metadata
    metadata?: {
        provisioningError?: string;
        retryCount?: number;
        [key: string]: any;
    };

    // MobiMatter / eSIM Specifics
    esim?: {
        iccid: string;
        lpa: string;
        qrData?: string;
        qrUrl?: string;
        smdpAddress?: string;
        activationCode?: string;
    };

    // Legacy fields (keep for backward compatibility if needed, or deprecate)
    mobimatterOrderId?: string;
    esimIccid?: string;
    esimSmdpAddress?: string;
    esimActivationCode?: string;
}

export interface Trip {
    id: string;
    userId: string;
    destination: string;
    duration: number;
    purpose: string;
    budget: string;
    itinerary: any; // Full JSON content
    createdAt: number;
}

export interface ProductCache {
    sku: string;
    data: unknown; // Full JSON from MobiMatter
    updatedAt: number;
}
