import { NextRequest, NextResponse } from "next/server";
import { airalo } from "@/services/airalo";

// GET /api/packages - List packages
export async function GET(request: NextRequest) {
    try {
        const searchParams = request.nextUrl.searchParams;
        const country = searchParams.get("country");
        const type = searchParams.get("type"); // local, global
        const page = parseInt(searchParams.get("page") || "1");
        const limit = parseInt(searchParams.get("limit") || "20");

        let response;

        if (country) {
            // Get packages for specific country
            response = await airalo.getCountryPackages(country);
        } else if (type === "global") {
            // Get global/regional packages
            response = await airalo.getGlobalPackages();
        } else {
            // Get all packages with pagination
            response = await airalo.getAllPackages({ page, limit });
        }

        // Transform packages for frontend
        const packages = response.data.map((pkg) => ({
            id: pkg.package_id,
            airaloPackageId: pkg.package_id,
            slug: pkg.slug,
            type: pkg.type,
            title: pkg.title,
            data: pkg.data,
            dataAmount: pkg.amount,
            validityDays: pkg.day,
            isUnlimited: pkg.is_unlimited,
            netPrice: pkg.net_price,
            retailPrice: pkg.price,
            ourPrice: calculateOurPrice(pkg.net_price),
            operatorTitle: pkg.operator.title,
            isRoaming: pkg.operator.is_roaming,
            operatorInfo: pkg.operator.info,
            countries: pkg.countries,
            planType: pkg.plan_type,
            activationPolicy: pkg.activation_policy,
            shortInfo: pkg.short_info,
        }));

        return NextResponse.json({
            packages,
            pagination: response.meta
                ? {
                    page: response.meta.current_page,
                    limit: response.meta.per_page,
                    total: response.meta.total,
                    totalPages: response.meta.last_page,
                }
                : null,
        });
    } catch (error) {
        console.error("Error fetching packages:", error);

        // Return mock data in development if Airalo credentials not set
        if (process.env.NODE_ENV === "development" && !process.env.AIRALO_CLIENT_ID) {
            return NextResponse.json({
                packages: getMockPackages(),
                pagination: { page: 1, limit: 20, total: 10, totalPages: 1 },
            });
        }

        return NextResponse.json(
            { error: "Failed to fetch packages" },
            { status: 500 }
        );
    }
}

// Calculate our selling price (add margin)
function calculateOurPrice(netPrice: number, marginPercent: number = 25): number {
    return Math.round((netPrice * (1 + marginPercent / 100)) * 100) / 100;
}

// Mock data for development
function getMockPackages() {
    // Exchange rate: 1 USD = 3500 MNT
    const usdToMnt = (usd: number) => Math.round(usd * 3500);

    return [
        // JAPAN - Multiple options
        {
            id: "jp-3d-1gb",
            airaloPackageId: "moshi-3days-1gb",
            slug: "japan",
            type: "sim",
            title: "Japan 1GB - 3 Days",
            data: "1 GB",
            dataAmount: 1024,
            validityDays: 3,
            isUnlimited: false,
            netPrice: 2.99,
            retailPrice: 4.00,
            ourPrice: usdToMnt(3.99),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Rechargeable"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Short trip data eSIM for Japan.",
        },
        {
            id: "jp-7d-3gb",
            airaloPackageId: "moshi-7days-3gb",
            slug: "japan",
            type: "sim",
            title: "Japan 3GB - 7 Days",
            data: "3 GB",
            dataAmount: 3072,
            validityDays: 7,
            isUnlimited: false,
            netPrice: 5.99,
            retailPrice: 8.00,
            ourPrice: usdToMnt(7.49),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Rechargeable"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Popular choice for Japan travelers.",
        },
        {
            id: "jp-15d-5gb",
            airaloPackageId: "moshi-15days-5gb",
            slug: "japan",
            type: "sim",
            title: "Japan 5GB - 15 Days",
            data: "5 GB",
            dataAmount: 5120,
            validityDays: 15,
            isUnlimited: false,
            netPrice: 9.99,
            retailPrice: 13.00,
            ourPrice: usdToMnt(12.49),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Extended validity"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Extended stay in Japan.",
        },
        {
            id: "jp-30d-10gb",
            airaloPackageId: "moshi-30days-10gb",
            slug: "japan",
            type: "sim",
            title: "Japan 10GB - 30 Days",
            data: "10 GB",
            dataAmount: 10240,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 17.99,
            retailPrice: 23.00,
            ourPrice: usdToMnt(21.99),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Best value"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Long stay with plenty of data.",
        },

        // SOUTH KOREA - Multiple options
        {
            id: "kr-5d-3gb",
            airaloPackageId: "sk-5days-3gb",
            slug: "south-korea",
            type: "sim",
            title: "Korea 3GB - 5 Days",
            data: "3 GB",
            dataAmount: 3072,
            validityDays: 5,
            isUnlimited: false,
            netPrice: 4.99,
            retailPrice: 7.00,
            ourPrice: usdToMnt(6.49),
            operatorTitle: "SK Telecom",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Fast speeds"],
            countries: ["KR"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Quick trip to Korea.",
        },
        {
            id: "kr-7d-5gb",
            airaloPackageId: "sk-7days-5gb",
            slug: "south-korea",
            type: "sim",
            title: "Korea 5GB - 7 Days",
            data: "5 GB",
            dataAmount: 5120,
            validityDays: 7,
            isUnlimited: false,
            netPrice: 7.99,
            retailPrice: 11.00,
            ourPrice: usdToMnt(9.99),
            operatorTitle: "SK Telecom",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Fast speeds"],
            countries: ["KR"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Week-long Korea adventure.",
        },
        {
            id: "kr-15d-10gb",
            airaloPackageId: "sk-15days-10gb",
            slug: "south-korea",
            type: "sim",
            title: "Korea 10GB - 15 Days",
            data: "10 GB",
            dataAmount: 10240,
            validityDays: 15,
            isUnlimited: false,
            netPrice: 14.99,
            retailPrice: 19.00,
            ourPrice: usdToMnt(17.99),
            operatorTitle: "SK Telecom",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Extended stay"],
            countries: ["KR"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Extended Korea exploration.",
        },

        // THAILAND - Multiple options
        {
            id: "th-7d-3gb",
            airaloPackageId: "ais-7days-3gb",
            slug: "thailand",
            type: "sim",
            title: "Thailand 3GB - 7 Days",
            data: "3 GB",
            dataAmount: 3072,
            validityDays: 7,
            isUnlimited: false,
            netPrice: 3.99,
            retailPrice: 6.00,
            ourPrice: usdToMnt(5.49),
            operatorTitle: "AIS",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["TH"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Budget-friendly Thailand eSIM.",
        },
        {
            id: "th-15d-8gb",
            airaloPackageId: "ais-15days-8gb",
            slug: "thailand",
            type: "sim",
            title: "Thailand 8GB - 15 Days",
            data: "8 GB",
            dataAmount: 8192,
            validityDays: 15,
            isUnlimited: false,
            netPrice: 8.99,
            retailPrice: 12.00,
            ourPrice: usdToMnt(10.99),
            operatorTitle: "AIS",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Great value"],
            countries: ["TH"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Extended Thailand stay.",
        },
        {
            id: "th-30d-20gb",
            airaloPackageId: "ais-30days-20gb",
            slug: "thailand",
            type: "sim",
            title: "Thailand 20GB - 30 Days",
            data: "20 GB",
            dataAmount: 20480,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 15.99,
            retailPrice: 20.00,
            ourPrice: usdToMnt(18.99),
            operatorTitle: "AIS",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Heavy user"],
            countries: ["TH"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Long stay with lots of data.",
        },

        // CHINA - Multiple options
        {
            id: "cn-7d-2gb",
            airaloPackageId: "china-7days-2gb",
            slug: "china",
            type: "sim",
            title: "China 2GB - 7 Days",
            data: "2 GB",
            dataAmount: 2048,
            validityDays: 7,
            isUnlimited: false,
            netPrice: 4.99,
            retailPrice: 7.00,
            ourPrice: usdToMnt(6.49),
            operatorTitle: "China Mobile",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Works with VPN"],
            countries: ["CN"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Business trip to China.",
        },
        {
            id: "cn-15d-5gb",
            airaloPackageId: "china-15days-5gb",
            slug: "china",
            type: "sim",
            title: "China 5GB - 15 Days",
            data: "5 GB",
            dataAmount: 5120,
            validityDays: 15,
            isUnlimited: false,
            netPrice: 9.99,
            retailPrice: 13.00,
            ourPrice: usdToMnt(11.99),
            operatorTitle: "China Mobile",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Works with VPN"],
            countries: ["CN"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Extended China visit.",
        },
        {
            id: "cn-30d-10gb",
            airaloPackageId: "china-30days-10gb",
            slug: "china",
            type: "sim",
            title: "China 10GB - 30 Days",
            data: "10 GB",
            dataAmount: 10240,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 17.99,
            retailPrice: 23.00,
            ourPrice: usdToMnt(20.99),
            operatorTitle: "China Mobile",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Works with VPN", "Best value"],
            countries: ["CN"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Long-term China stay.",
        },
        {
            id: "cn-30d-20gb",
            airaloPackageId: "china-30days-20gb",
            slug: "china",
            type: "sim",
            title: "China 20GB - 30 Days",
            data: "20 GB",
            dataAmount: 20480,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 29.99,
            retailPrice: 38.00,
            ourPrice: usdToMnt(34.99),
            operatorTitle: "China Mobile",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Works with VPN"],
            countries: ["CN"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Heavy data user in China.",
        },

        // Additional Japan packages
        {
            id: "jp-1d-500mb",
            airaloPackageId: "moshi-1day-500mb",
            slug: "japan",
            type: "sim",
            title: "Japan 500MB - 1 Day",
            data: "500 MB",
            dataAmount: 512,
            validityDays: 1,
            isUnlimited: false,
            netPrice: 1.99,
            retailPrice: 3.00,
            ourPrice: usdToMnt(2.49),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Quick day trip.",
        },
        {
            id: "jp-7d-5gb",
            airaloPackageId: "moshi-7days-5gb",
            slug: "japan",
            type: "sim",
            title: "Japan 5GB - 7 Days",
            data: "5 GB",
            dataAmount: 5120,
            validityDays: 7,
            isUnlimited: false,
            netPrice: 8.99,
            retailPrice: 12.00,
            ourPrice: usdToMnt(10.99),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "More data for active users.",
        },
        {
            id: "jp-30d-20gb",
            airaloPackageId: "moshi-30days-20gb",
            slug: "japan",
            type: "sim",
            title: "Japan 20GB - 30 Days",
            data: "20 GB",
            dataAmount: 20480,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 29.99,
            retailPrice: 38.00,
            ourPrice: usdToMnt(34.99),
            operatorTitle: "SoftBank",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM", "Heavy user"],
            countries: ["JP"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Maximum data for Japan.",
        },

        // Additional Korea packages
        {
            id: "kr-3d-1gb",
            airaloPackageId: "sk-3days-1gb",
            slug: "south-korea",
            type: "sim",
            title: "Korea 1GB - 3 Days",
            data: "1 GB",
            dataAmount: 1024,
            validityDays: 3,
            isUnlimited: false,
            netPrice: 3.49,
            retailPrice: 5.00,
            ourPrice: usdToMnt(4.49),
            operatorTitle: "SK Telecom",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["KR"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Weekend in Korea.",
        },
        {
            id: "kr-30d-20gb",
            airaloPackageId: "sk-30days-20gb",
            slug: "south-korea",
            type: "sim",
            title: "Korea 20GB - 30 Days",
            data: "20 GB",
            dataAmount: 20480,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 27.99,
            retailPrice: 35.00,
            ourPrice: usdToMnt(32.99),
            operatorTitle: "SK Telecom",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["KR"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Long-term Korea stay.",
        },

        // Additional Thailand packages
        {
            id: "th-3d-1gb",
            airaloPackageId: "ais-3days-1gb",
            slug: "thailand",
            type: "sim",
            title: "Thailand 1GB - 3 Days",
            data: "1 GB",
            dataAmount: 1024,
            validityDays: 3,
            isUnlimited: false,
            netPrice: 2.49,
            retailPrice: 4.00,
            ourPrice: usdToMnt(3.49),
            operatorTitle: "AIS",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["TH"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Quick Bangkok trip.",
        },
        {
            id: "th-30d-15gb",
            airaloPackageId: "ais-30days-15gb",
            slug: "thailand",
            type: "sim",
            title: "Thailand 15GB - 30 Days",
            data: "15 GB",
            dataAmount: 15360,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 14.99,
            retailPrice: 19.00,
            ourPrice: usdToMnt(17.99),
            operatorTitle: "AIS",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["TH"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Month-long Thailand adventure.",
        },

        // USA packages
        {
            id: "us-7d-3gb",
            airaloPackageId: "usa-7days-3gb",
            slug: "usa",
            type: "sim",
            title: "USA 3GB - 7 Days",
            data: "3 GB",
            dataAmount: 3072,
            validityDays: 7,
            isUnlimited: false,
            netPrice: 8.99,
            retailPrice: 12.00,
            ourPrice: usdToMnt(10.99),
            operatorTitle: "AT&T",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["US"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Week in USA.",
        },
        {
            id: "us-15d-10gb",
            airaloPackageId: "usa-15days-10gb",
            slug: "usa",
            type: "sim",
            title: "USA 10GB - 15 Days",
            data: "10 GB",
            dataAmount: 10240,
            validityDays: 15,
            isUnlimited: false,
            netPrice: 19.99,
            retailPrice: 26.00,
            ourPrice: usdToMnt(23.99),
            operatorTitle: "AT&T",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["US"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Extended USA trip.",
        },
        {
            id: "us-30d-20gb",
            airaloPackageId: "usa-30days-20gb",
            slug: "usa",
            type: "sim",
            title: "USA 20GB - 30 Days",
            data: "20 GB",
            dataAmount: 20480,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 34.99,
            retailPrice: 45.00,
            ourPrice: usdToMnt(39.99),
            operatorTitle: "AT&T",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["US"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Month in USA.",
        },
        {
            id: "us-30d-50gb",
            airaloPackageId: "usa-30days-50gb",
            slug: "usa",
            type: "sim",
            title: "USA 50GB - 30 Days",
            data: "50 GB",
            dataAmount: 51200,
            validityDays: 30,
            isUnlimited: false,
            netPrice: 59.99,
            retailPrice: 75.00,
            ourPrice: usdToMnt(69.99),
            operatorTitle: "AT&T",
            isRoaming: true,
            operatorInfo: ["4G/LTE Data eSIM"],
            countries: ["US"],
            planType: "data",
            activationPolicy: "first-usage",
            shortInfo: "Maximum data for USA.",
        },
    ];
}
